// Generated by jails from art_ent_payout_repository. Clean hand edits survive regeneration.
package com.example.demo.repository;

import com.example.demo.domain.Payout;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

public interface PayoutRepository {

    Optional<Payout> findById(UUID id);

    List<Payout> findAll();

    Payout save(Payout payout);

    boolean deleteById(UUID id);

    // Reader extensions belong below this stable boundary.
}
