// Generated by jails from art_ent_ticket_record. Clean hand edits survive regeneration.
package com.example.demo.domain;

import java.util.Objects;

public record Ticket(
    long id,
    String subject
) {

    public Ticket {
        Objects.requireNonNull(subject, "subject");
        subject = subject.trim();
        if (subject.isEmpty()) {
            throw new IllegalArgumentException("subject must not be blank");
        }
    }
}
