// Generated by jails from art_ent_payout_dto_response. Clean hand edits survive regeneration.
package com.example.demo.web;

import com.example.demo.domain.Payout;
import java.util.UUID;

public record PayoutResponse(
    UUID id,
    long amount
) {

    public static PayoutResponse fromDomain(Payout payout) {
        return new PayoutResponse(
                payout.id(),
                payout.amount());
    }
}
