@baseUrl = http://localhost:8080

### Create Inbox
POST {{baseUrl}}/inboxes
Content-Type: application/json

{
  "id": "00000000-0000-0000-0000-000000000001",
  "workspaceId": "00000000-0000-0000-0000-000000000001",
  "name": "sample-name",
  "channel": "WEB",
  "createdAt": "2026-01-01T00:00:00Z",
  "updatedAt": "2026-01-01T00:00:00Z"
}

### List Inbox
GET {{baseUrl}}/inboxes
Accept: application/json
