-- Generated by jails from the accepted model.
create table tickets (
    id bigint generated always as identity not null primary key,
    subject text not null check (length(btrim(subject)) > 0),
    status text
);
