// Generated by jails from art_ent_item_service. Clean hand edits survive regeneration.
package com.example.demo.service;

import com.example.demo.domain.Item;
import com.example.demo.repository.ItemRepository;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.UUID;
import org.springframework.stereotype.Component;

/**
 * What the application can do with {@link Item}.
 *
 * <p>Depends on the port, not on an adapter, so a test can hand it an
 * in-memory implementation and never start a database.
 */
@Component
public class ItemService {

    private final ItemRepository repository;

    public ItemService(ItemRepository repository) {
        this.repository = Objects.requireNonNull(repository, "repository is required");
    }

    public Optional<Item> byId(UUID id) {
        return repository.findById(id);
    }

    public List<Item> all() {
        return repository.findAll();
    }

    public Item save(Item item) {
        return repository.save(item);
    }

    public boolean delete(UUID id) {
        return repository.deleteById(id);
    }

    // Reader-owned application methods belong below this stable boundary.
}
