// Generated by jails from art_ent_note_record. Clean hand edits survive regeneration.
package com.example.demo.domain;

import java.util.Objects;
import java.util.UUID;

public record Note(
    UUID id,
    String title,
    String status
) {

    public Note {
        Objects.requireNonNull(id, "id");
        Objects.requireNonNull(title, "title");
        title = title.trim();
        if (title.isEmpty()) {
            throw new IllegalArgumentException("title must not be blank");
        }
        Objects.requireNonNull(status, "status");
    }
}
