// Generated by jails from art_op_transaction_settled_publisher. Clean hand edits survive regeneration.
package com.example.demo.messaging;

import com.example.demo.domain.events.TransactionSettledEvent;
import java.util.concurrent.CompletableFuture;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.kafka.support.SendResult;
import org.springframework.stereotype.Component;

/**
 * Publishes {@link TransactionSettledEvent}.
 *
 * <p>The topic is a property, not a constant: the same jar has to run against
 * a local broker, a shared staging one and production, and those rarely agree
 * on names.
 *
 * <p>Keyed on the event's own id, which spreads records about one
 * entity across every partition: there is <em>no</em> per-entity order
 * here. Declare the event on an entity whose identity the payload
 * carries to get one.
 * */
@Component
public class TransactionSettledPublisher {

    private final KafkaTemplate<String, TransactionSettledEvent> kafka;
    private final String topic;

    public TransactionSettledPublisher(
            KafkaTemplate<String, TransactionSettledEvent> kafka,
            @Value("${topics.transaction-settled:transaction-settled}") String topic) {
        this.kafka = kafka;
        this.topic = topic;
    }

    /** The returned acknowledgement lets durable callers mark success only after Kafka accepts it. */
    public CompletableFuture<SendResult<String, TransactionSettledEvent>> publish(TransactionSettledEvent event) {
        return kafka.send(topic, String.valueOf(event.id()), event);
    }
}
