// Generated by jails from art_cmp_service_billing_test. Clean hand edits survive regeneration.
package com.example.demo.service;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

class BillingServiceTest {

    @Test
    void instantiates() {
        assertNotNull(new BillingService());
    }
}
