// Generated by jails from art_ent_payout_dto_response. Clean hand edits survive regeneration.
package com.example.demo.web;

import com.example.demo.domain.Payout;
import com.example.demo.domain.PayoutStatus;
import java.time.Instant;
import java.util.UUID;

public record PayoutResponse(
    UUID id,
    long amount,
    PayoutStatus status,
    long version,
    Instant createdAt
) {

    public static PayoutResponse fromDomain(Payout payout) {
        return new PayoutResponse(
                payout.id(),
                payout.amount(),
                payout.status(),
                payout.version(),
                payout.createdAt());
    }
}
