// Generated by jails from art_ent_note_dto_response. Clean hand edits survive regeneration.
package com.example.demo.web;

import com.example.demo.domain.Note;
import com.example.demo.domain.SenderType;

public record NoteResponse(
    long id,
    long authorId,
    String body,
    SenderType senderType
) {

    public static NoteResponse fromDomain(Note note) {
        return new NoteResponse(
                note.id(),
                note.authorId(),
                note.body(),
                note.senderType());
    }
}
