// Generated by jails from art_ent_note_record. Clean hand edits survive regeneration.
package com.example.demo.domain;

import java.time.Instant;
import java.util.Objects;
import java.util.Optional;

public record Note(
    String title,
    Optional<String> body,
    Instant at
) {

    public Note {
        Objects.requireNonNull(title, "title");
        title = title.trim();
        if (title.isEmpty()) {
            throw new IllegalArgumentException("title must not be blank");
        }
        body = Objects.requireNonNullElse(body, Optional.empty());
        Objects.requireNonNull(at, "at");
    }
}
