// Generated by jails from art_ent_author_record. Clean hand edits survive regeneration.
package com.example.demo.domain;

import java.util.Objects;

public record Author(
    long id,
    String email
) {

    public Author {
        Objects.requireNonNull(email, "email");
        email = email.trim();
        if (email.isEmpty()) {
            throw new IllegalArgumentException("email must not be blank");
        }
    }
}
