// Generated by jails from art_ent_widget_dto_request. Clean hand edits survive regeneration.
package com.example.demo.web;

import com.example.demo.domain.TimeOrderedUuid;
import com.example.demo.domain.Widget;
import jakarta.validation.constraints.NotBlank;

public record WidgetRequest(
    @NotBlank String name
) {

    /**
     * The domain row this request describes, with every server-assigned
     * value supplied here rather than taken from the caller.
     */
    public Widget toDomain() {
        return new Widget(
                TimeOrderedUuid.next(),
                name);
    }
}
