// Generated by jails from art_ent_widget_dto_response. Clean hand edits survive regeneration.
package com.example.demo.web;

import com.example.demo.domain.Widget;
import java.util.UUID;

public record WidgetResponse(
    UUID id,
    String name
) {

    public static WidgetResponse fromDomain(Widget widget) {
        return new WidgetResponse(
                widget.id(),
                widget.name());
    }
}
