// Generated by jails from art_cmp_job_reconcile_test. Clean hand edits survive regeneration.
package com.example.demo.jobs;

import static org.assertj.core.api.Assertions.assertThatCode;

import org.junit.jupiter.api.Test;

/**
 * Calls the work directly rather than waiting for a schedule.
 *
 * <p>A test that sleeps until the scheduler fires is slow and flaky, and it
 * tests Spring's scheduler rather than this job. What is worth asserting here
 * is that {@code run()} does not propagate -- because an exception escaping a
 * scheduled method cancels every future run.
 */
class ReconcileJobTest {

    private final ReconcileJob job = new ReconcileJob();

    @Test
    void theWorkRuns() {
        assertThatCode(job::work).doesNotThrowAnyException();
    }

    @Test
    void aFailureNeverEscapesAndCancelsTheSchedule() {
        ReconcileJob failing =
                new ReconcileJob() {
                    @Override
                    void work() {
                        throw new IllegalStateException("boom");
                    }
                };
        assertThatCode(failing::run).doesNotThrowAnyException();
    }
}
