@baseUrl = http://localhost:8080

### Create Note
POST {{baseUrl}}/notes
Content-Type: application/json

{
  "id": "00000000-0000-0000-0000-000000000001",
  "title": "sample-title",
  "amount": 1,
  "createdAt": "2026-01-01T00:00:00Z"
}
