// Generated by jails from art_ent_payout_record. Clean hand edits survive regeneration.
package com.example.demo.domain;

import java.time.Instant;
import java.util.Objects;
import java.util.UUID;

public record Payout(
    UUID id,
    long amount,
    PayoutStatus status,
    long version,
    Instant createdAt
) {

    public Payout {
        Objects.requireNonNull(id, "id");
        if (amount <= 0) {
            throw new IllegalArgumentException("amount must be positive");
        }
        Objects.requireNonNull(status, "status");
        if (version < 0) {
            throw new IllegalArgumentException("version must be nonnegative");
        }
        Objects.requireNonNull(createdAt, "createdAt");
    }
}
