-- Generated by jails from the accepted semantic schema.
alter table notes add column created_at timestamptz;
update notes set created_at = '2026-08-25T12:00:00Z' where created_at is null;
alter table notes alter column created_at set not null;
