@baseUrl = http://localhost:8080

### Create Merchant
POST {{baseUrl}}/merchants
Content-Type: application/json

{
  "id": "00000000-0000-0000-0000-000000000001",
  "reference": "sample-reference",
  "displayName": "sample-displayName"
}
