-- Generated by jails from the accepted model.
create table notes (
    id uuid not null primary key,
    title text not null check (length(btrim(title)) > 0),
    status text not null
);
create index idx_notes_status on notes (status);
