-- Generated by jails from the accepted semantic schema.
create table note (
    id uuid not null primary key,
    title text not null check (length(btrim(title)) > 0),
    status text not null
);
create index idx_note_status on note (status);
