// Generated by jails from art_ent_payout_record. Clean hand edits survive regeneration.
package com.example.demo.domain;

import java.util.Objects;
import java.util.UUID;

public record Payout(
    UUID id,
    long amount
) {

    public Payout {
        Objects.requireNonNull(id, "id");
    }
}
