// Generated by jails from art_op_transaction_settled_event. Clean hand edits survive regeneration.
package com.example.demo.domain.events;

import java.util.Objects;
import java.util.UUID;

public record TransactionSettledEvent(
    UUID id
) {

    public TransactionSettledEvent {
        Objects.requireNonNull(id, "id");
    }
}
