// Generated by jails from art_ent_operator_repository. Clean hand edits survive regeneration.
package com.example.demo.repository;

import com.example.demo.domain.Operator;
import java.util.List;
import java.util.Optional;

public interface OperatorRepository {

    Optional<Operator> findById(long id);

    List<Operator> findAll();

    Operator save(Operator operator);

    boolean deleteById(long id);

    // Reader extensions belong below this stable boundary.
}
