// Generated by jails from art_cap_db_ent_item_repository_it. Clean hand edits survive regeneration.
package com.example.demo.adapters.jdbc;

import com.example.demo.TestcontainersConfig;
import com.example.demo.domain.Item;
import com.example.demo.repository.ItemRepository;
import com.example.demo.repository.ItemRepositoryContract;
import java.time.Instant;
import java.util.UUID;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Import;
import org.springframework.transaction.annotation.Transactional;

@Import(TestcontainersConfig.class)
@SpringBootTest
@Transactional
class JdbcItemRepositoryIT {

    @Autowired
    private ItemRepository repository;

    @Test
    void satisfiesTheItemRepositoryContractAgainstTheRealDatabase() {
        ItemRepositoryContract.savesReadsAndDeletes(
                repository, new Item(UUID.fromString("00000000-0000-0000-0000-000000000001"), UUID.fromString("00000000-0000-0000-0000-000000000001"), "sample", Instant.parse("2026-01-01T00:00:00Z")));
    }

    // Reader-owned cases belong below this stable boundary.
}
