// Generated by jails from art_op_open_ticket_http. Clean hand edits survive regeneration.
package com.example.demo.adapters.http;

import com.example.demo.application.commands.OpenTicketCommand;
import com.example.demo.domain.Ticket;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

@RestController
public final class OpenTicketController {

    private final OpenTicketCommand operation;

    public OpenTicketController(OpenTicketCommand operation) {
        this.operation = operation;
    }

    @RequestMapping(path = "/actions/open-ticket", method = RequestMethod.POST)
    public Ticket execute(@RequestBody OpenTicketCommand.Input input) {
        return operation.execute(input);
    }
}
