// Generated by jails from art_ent_message_repository. Clean hand edits survive regeneration.
package com.example.demo.repository;

import com.example.demo.domain.Message;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

public interface MessageRepository {

    Optional<Message> findById(UUID id);

    List<Message> findAll();

    Message save(Message message);

    boolean deleteById(UUID id);

    // Reader extensions belong below this stable boundary.
}
