// Generated by jails from art_rel_ent_item_item_owner_association_it. Clean hand edits survive regeneration.
package com.example.demo.adapters.jdbc;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.example.demo.TestcontainersConfig;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Import;
import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.transaction.annotation.Transactional;

@Import(TestcontainersConfig.class)
@SpringBootTest
@Transactional
class ItemOwnerAssociationIT {

    @Autowired
    private JdbcClient db;

    /**
     * The catalogue, because a mapping written backwards is a
     * constraint that exists and pairs the wrong columns.
     */
    @Test
    void schemaCarriesTheExactOrderedRelationship() {
        String mapping = db.sql("""
                        select string_agg(child_column.attname || '=' || parent_column.attname,
                                         ',' order by pair.ordinality)
                        from pg_constraint relation
                        cross join lateral unnest(relation.conkey, relation.confkey)
                            with ordinality as pair(child_number, parent_number, ordinality)
                        join pg_attribute child_column
                          on child_column.attrelid = relation.conrelid
                         and child_column.attnum = pair.child_number
                        join pg_attribute parent_column
                          on parent_column.attrelid = relation.confrelid
                         and parent_column.attnum = pair.parent_number
                        where relation.contype = 'f' and relation.conname = :constraint
                        """)
                .param("constraint", "fk_items_item_owner")
                .query(String.class)
                .single();

        assertThat(mapping).isEqualTo("owner_id=id");
    }

    /**
     * And the database enforces it, rather than merely recording it.
     *
     * <p>The rejection is not asked to name <em>which</em> key it broke:
     * a child table with several relations trips whichever constraint
     * PostgreSQL checks first, and that order is the migration's
     * rather than this proof's. Which columns this one pairs is
     * settled above, where nothing else can confound it.
     */
    @Test
    void aRowNamingNoParentIsRejected() {
        assertThatThrownBy(() -> db.sql(
                        "insert into items (id, owner_id, name, created_at) values ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000002', 'sample', '2026-01-01T00:00:00Z')")
                .update())
                .isInstanceOf(DataAccessException.class)
                .rootCause()
                .hasMessageContaining("violates foreign key constraint")
                .hasMessageContaining("items");
    }
}
