// Generated by jails from art_ent_note_repository_memory_test. Clean hand edits survive regeneration.
package com.example.demo.adapters.memory;

import com.example.demo.domain.Note;
import com.example.demo.repository.NoteRepositoryContract;
import java.util.UUID;
import org.junit.jupiter.api.Test;

/**
 * The fake is held to the same contract as the real adapter.
 *
 * <p>No database and no application context: the in-memory adapter is an
 * ordinary object with a constructor, which is the whole reason it exists.
 * The assertions live in {@code NoteRepositoryContract} so this and the
 * JDBC adapter's integration test cannot come to disagree about them.
 */
class InMemoryNoteRepositoryTest {

    @Test
    void satisfiesTheNoteRepositoryContract() {
        NoteRepositoryContract.savesReadsAndDeletes(
                new InMemoryNoteRepository(), new Note(UUID.fromString("00000000-0000-0000-0000-000000000001"), "sample"));
    }

    // Reader-owned cases belong below this stable boundary.
}
