-- Generated by jails from the accepted semantic schema.
create table notes (
    id bigint generated always as identity not null primary key,
    author_id bigint not null,
    body text not null check (length(btrim(body)) > 0),
    sender_type text not null
);
