// Generated by jails from art_op_post_admin_note_command. Clean hand edits survive regeneration.
package com.example.demo.application.commands;

import com.example.demo.domain.Note;
import java.util.Objects;

public interface PostAdminNoteCommand {
    String ROUTE = "POST /admin_api/notes";

    Note execute(Input input);

    public record Input(
        long authorId,
        String body
    ) {

        public Input {
            Objects.requireNonNull(body, "body");
            body = body.trim();
            if (body.isEmpty()) {
                throw new IllegalArgumentException("body must not be blank");
            }
        }
    }
}
