-- Generated by jails from the accepted semantic schema.
create table tickets (
    id bigint generated always as identity not null primary key,
    subject text not null check (length(btrim(subject)) > 0)
);
