// Generated by jails from art_ent_owner_http. Clean hand edits survive regeneration.
package com.example.demo.ports.http;

import com.example.demo.domain.Owner;

public interface OwnerHttpPort {

    Owner create(Owner request);
}
