// Generated by jails from art_ent_ticket_repository. Clean hand edits survive regeneration.
package com.example.demo.repository;

import com.example.demo.domain.Ticket;
import java.util.List;
import java.util.Optional;

public interface TicketRepository {

    Optional<Ticket> findById(long id);

    List<Ticket> findAll();

    Ticket save(Ticket ticket);

    boolean deleteById(long id);

    // Reader extensions belong below this stable boundary.
}
