//! Byte-level snapshots of everything jails generates.
//!
//! Every generated byte is pinned, so a change to a generator is visible and
//! deliberate. The suite is end-to-end rather than one snapshot per template:
//! each scenario runs through the same path a user takes, so a template
//! rendered with the wrong arguments is caught as well as one whose text
//! changed.
//!
//! ## Updating
//!
//! ```text
//! UPDATE_GOLDEN=1 cargo test --test golden
//! ```
//!
//! Then **read the diff**: `git diff tests/golden` is the review. Regenerating
//! without reading is how a snapshot suite stops being an oracle and starts
//! being a rubber stamp, which is why the assertions below also check semantic
//! properties a blind regeneration would not fix.

mod common;

use common::scenarios::{Fixture, SCENARIOS, Scenario};
use common::*;
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

fn golden_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/golden")
}

fn updating() -> bool {
    std::env::var_os("UPDATE_GOLDEN").is_some_and(|v| v != "0")
}

/// Every file under `dir`, relative path -> contents, sorted.
///
/// A `BTreeMap` so the comparison is order-independent and the failure names
/// the file rather than a diff of the whole tree.
fn snapshot(dir: &Path) -> BTreeMap<String, String> {
    let mut found = BTreeMap::new();
    collect(dir, dir, &mut found);
    found
}

/// The project-owned `.jails/` files a golden snapshot holds.
///
/// **`model.jdl` is the authored source every scenario starts from**, and the
/// most load-bearing entry here: the snapshot is the only place the
/// declaration a scenario's `g` commands built up is visible beside the tree
/// they produced. `ledger.toml` is jails' registry and `app.toml` the reader's
/// manifest. Everything else under `.jails/` is the executor's, and is listed
/// in [`EXECUTOR_STATE`] rather than excluded by a wildcard, so a new one is a
/// deliberate entry rather than a silent omission.
///
/// The architecture policy is not here because it is not under `.jails/`: it
/// is `[[architecture.allow]]` in `jails.toml`, an ordinary project file the
/// walk already collects.
const SNAPSHOTTED_PROJECT_FILES: [&str; 3] = ["model.jdl", "ledger.toml", "app.toml"];

/// The executor's own state, which is never snapshotted.
///
/// Named after content and transaction hashes: an object is
/// `objects/sha256/ab/cdef...` and a receipt is keyed by a transaction id, so
/// both change whenever any input to any scenario changes. A golden holding
/// them would churn on every template edit and say nothing about the Java
/// jails generated -- which is what the goldens exist to pin.
///
/// The locks are excluded for a different reason: they are empty files whose
/// presence depends on whether a run was interrupted, so they are not output
/// at all.
const EXECUTOR_STATE: [&str; 11] = [
    ".jails/objects/",
    ".jails/transactions/",
    ".jails/receipts/",
    ".jails/lock",
    ".jails/effects.lock",
    // The canonical executor's, and empty for the same reason the two above
    // are: a lock file's contents are never the point, and snapshotting one
    // records a byte count as though it were output.
    ".jails/apply.lock",
    // The merge base: one file per managed path, holding exactly the bytes
    // of the file beside it in this same snapshot. Goldening it would put a
    // second verbatim copy of every generated file inside the snapshot of
    // those files, doubling the corpus and saying nothing the first copy
    // does not.
    ".jails/base/",
    // One run's scratch, and the last applied plan inside it: a verbatim
    // copy of every blob the scenario wrote, which is the same reason the
    // compiler lock below is not snapshotted -- it would churn on every
    // template edit and say nothing the generated files beside it do not.
    ".jails/run/",
    // The compiler lock is goldened *as a format* in
    // `tests/protocol-golden/compiler-lock-v5.json`, where the base is a
    // manifest of digests and the bytes are the files beside it. Holding it here as well would put a second,
    // verbatim copy of the whole generated tree inside the snapshot of that
    // same tree, changing whenever any template does and saying nothing the
    // files beside it do not.
    ".jails/compiler.lock.json",
    // The executor's marker saying which of its own files are scratch. Fixed
    // bytes, identical in every scenario, and about `.jails/` rather than
    // about anything a scenario generated -- 63 copies of four lines would
    // say only that the constant is still the constant, which a unit test
    // beside it says once.
    ".jails/.gitignore",
    // And the marker saying how git should treat the lock, for the same
    // reason: fixed bytes about `.jails/` rather than about anything a
    // scenario generated.
    ".jails/.gitattributes",
];

/// Whether this path is the executor's bookkeeping rather than jails' output.
fn executor_state(rel: &str) -> bool {
    EXECUTOR_STATE
        .iter()
        .any(|prefix| match prefix.ends_with('/') {
            true => rel.starts_with(prefix),
            false => rel == *prefix,
        })
}

fn collect(root: &Path, dir: &Path, out: &mut BTreeMap<String, String>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            // `target/` is build output, not something jails generated.
            if path.file_name().is_some_and(|n| n == "target") {
                continue;
            }
            collect(root, &path, out);
            continue;
        }
        let rel = path
            .strip_prefix(root)
            .unwrap()
            .to_string_lossy()
            .replace('\\', "/");
        if executor_state(&rel) {
            continue;
        }
        match fs::read_to_string(&path) {
            Ok(text) => {
                out.insert(rel, text);
            }
            // A binary file would not be jails' output; record its presence
            // so an accidental one is still visible.
            Err(_) => {
                out.insert(rel, "<non-utf8>".to_string());
            }
        }
    }
}

/// What the fixture puts there before jails runs. Subtracted from the
/// snapshot so the goldens hold only what jails itself produced -- otherwise
/// every scenario carries a copy of the fixture pom and the diff on a
/// template change is buried.
///
/// **Computed once per fixture, not once per scenario.** The fixture writers
/// take no argument but the directory, so the answer cannot differ between
/// scenarios.
fn fixture_files(fixture: Fixture) -> &'static BTreeMap<String, String> {
    fn compute(fixture: Fixture) -> BTreeMap<String, String> {
        let dir = temp_dir("golden-baseline");
        match fixture {
            Fixture::Plain => write_plain_fixture(&dir),
            Fixture::Spring => write_spring_fixture(&dir),
        }
        let files = snapshot(&dir);
        fs::remove_dir_all(&dir).ok();
        files
    }
    static PLAIN: std::sync::OnceLock<BTreeMap<String, String>> = std::sync::OnceLock::new();
    static SPRING: std::sync::OnceLock<BTreeMap<String, String>> = std::sync::OnceLock::new();
    match fixture {
        Fixture::Plain => PLAIN.get_or_init(|| compute(Fixture::Plain)),
        Fixture::Spring => SPRING.get_or_init(|| compute(Fixture::Spring)),
    }
}

fn run_scenario(scenario: &Scenario) -> BTreeMap<String, String> {
    let root = common::scenarios::prepare(scenario);
    let baseline = fixture_files(scenario.fixture);

    common::scenarios::run_steps(&root, scenario);

    let mut files = snapshot(&root);
    // Keep a file the fixture also had only when jails changed it (pom.xml,
    // application.properties): identical content means jails left it alone.
    files.retain(|path, contents| baseline.get(path) != Some(contents));
    // A seed file is the scenario's input, not jails' output.
    for (rel, _) in scenario.seed {
        files.remove(*rel);
    }
    fs::remove_dir_all(&root).ok();
    files
}

/// One scenario, generated and compared against its golden directory.
///
/// A cell of the table below, and independent of every other one: its own
/// temporary tree, its own `jails` processes and its own golden directory
/// under `tests/golden/`. That is what lets the table be scheduled rather
/// than walked.
fn golden_mismatches_for(scenario: &Scenario) -> Vec<String> {
    let mut mismatches: Vec<String> = Vec::new();
    let root = golden_root();
    let produced = run_scenario(scenario);
    let dir = root.join(scenario.name);

    if updating() {
        fs::remove_dir_all(&dir).ok();
        for (rel, contents) in &produced {
            let path = dir.join(rel);
            fs::create_dir_all(path.parent().unwrap()).unwrap();
            fs::write(&path, contents).unwrap();
        }
        return mismatches;
    }

    let expected = snapshot(&dir);
    if expected.is_empty() {
        mismatches.push(format!(
            "scenario `{}` has no golden files -- run `UPDATE_GOLDEN=1 cargo test --test golden`",
            scenario.name
        ));
        return mismatches;
    }
    for (rel, want) in &expected {
        match produced.get(rel) {
            None => mismatches.push(format!("{}/{rel}: no longer generated", scenario.name)),
            Some(got) if got != want => {
                mismatches.push(format!("{}/{rel}: contents changed", scenario.name))
            }
            Some(_) => {}
        }
    }
    for rel in produced.keys() {
        if !expected.contains_key(rel) {
            mismatches.push(format!("{}/{rel}: newly generated", scenario.name));
        }
    }
    mismatches
}

#[test]
fn generated_output_matches_the_golden_snapshots() {
    let mismatches: Vec<String> = common::parallel::map_recording(
        "golden-snapshots",
        SCENARIOS,
        |scenario| scenario.name.to_string(),
        golden_mismatches_for,
    )
    .into_iter()
    .flatten()
    .collect();

    assert!(
        mismatches.is_empty(),
        "generated output changed in {} place(s):\n  {}\n\n\
         If the change is intended: UPDATE_GOLDEN=1 cargo test --test golden, \
         then read `git diff tests/golden` before committing.",
        mismatches.len(),
        mismatches.join("\n  ")
    );
}

/// A snapshot suite that is only ever regenerated stops being an oracle. These
/// are properties a blind `UPDATE_GOLDEN=1` would not restore, so they fail
/// loudly rather than absorbing a regression into the new baseline.
#[test]
fn the_goldens_still_hold_the_properties_that_matter() {
    if updating() {
        return;
    }
    let root = golden_root();
    let all: Vec<(String, String)> = SCENARIOS
        .iter()
        .flat_map(|s| {
            snapshot(&root.join(s.name))
                .into_iter()
                .map(move |(rel, text)| (format!("{}/{rel}", s.name), text))
        })
        .collect();
    assert!(!all.is_empty(), "no goldens recorded yet");

    // One registry, not several. The gate is a property of the output, so it
    // is checked here rather than as a source measurement, and it is
    // **closed rather than counted**: every `.jails/` entry has to be one this
    // list names, and only the registry half is snapshotted. The executor's
    // own bookkeeping in the same directory -- an object store, a transaction
    // log, receipts and locks -- is named after content and transaction
    // hashes, and snapshotting it would make every golden churn on any change
    // to any input. A second registry growing back fails, and so does an
    // executor directory nobody wrote down.
    let mut bookkeeping: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for (path, _) in &all {
        if let Some((scenario, rest)) = path.split_once("/.jails/") {
            bookkeeping
                .entry(scenario.to_string())
                .or_default()
                .push(rest.to_string());
        }
    }
    assert!(!bookkeeping.is_empty(), "no scenario recorded a .jails/");
    for (scenario, entries) in &bookkeeping {
        for entry in entries {
            // **Nothing under `.jails/` is output.** Managed Java, SQL and
            // resources live beside the reader's own under `src/`, and the
            // lock says which are jails'; a generated file appearing here
            // again is the managed tree growing back.
            assert!(
                SNAPSHOTTED_PROJECT_FILES.contains(&entry.as_str()),
                "{scenario}: `.jails/{entry}` is neither project-owned source \
                 nor the executor's bookkeeping. A second registry must not \
                 grow back, and no output belongs under `.jails/`; \
                 a new executor path belongs in EXECUTOR_STATE with the reason \
                 it is not snapshotted."
            );
        }
    }

    for (path, text) in &all {
        if !path.ends_with(".java") {
            continue;
        }
        // `{{` is `format!`'s escape for a literal brace and must never
        // survive into output. `}}` is *not* checkable the same way: it
        // occurs legitimately in Javadoc, where a JSON example inside
        // `{@code ...}` ends `...}}`. One-sided is the honest check.
        assert!(
            !text.contains("{{"),
            "{path}: generated Java contains an unexpanded escaped brace"
        );
        // An unsubstituted placeholder compiles nowhere.
        for marker in ["{name}", "{pkg}", "{Name}", "{package}"] {
            assert!(
                !text.contains(marker),
                "{path}: unsubstituted placeholder `{marker}`"
            );
        }
        // A managed file opens with its provenance banner, which is how a
        // merge-managed artifact says which declaration it came from and that
        // clean hand edits survive. A file without a banner opens with the
        // package or a Javadoc. Both are checked exactly rather than the
        // assertion being loosened to "starts with anything": what this
        // catches is a stray blank line or leftover template preamble.
        let banner = text.starts_with("// Generated by jails from ");
        assert!(
            banner || text.starts_with("package ") || text.starts_with("/**"),
            "{path}: a generated Java file should start with its package, its \
             Javadoc, or its provenance banner"
        );
        if banner {
            let body = text.split_once('\n').map_or("", |(_, rest)| rest);
            assert!(
                body.starts_with("package "),
                "{path}: the provenance banner is not followed by the package \
                 declaration"
            );
        }
        // palantir-java-format removes both of these, so leaving one in means
        // `add format` -- which jails installs itself -- fails `jails check`
        // on a project whose every line jails wrote. `tidy_blank_lines` is
        // the write-path rule; this is what keeps a new template honest.
        // A blank line inside a text block is data, and is left alone.
        let mut in_text_block = false;
        let mut previous_blank = false;
        for (number, line) in text.lines().enumerate() {
            let blank = line.trim().is_empty();
            assert!(
                !(blank && previous_blank),
                "{path}:{}: two blank lines in a row -- palantir-java-format removes one",
                number + 1
            );
            if line.matches("\"\"\"").count() % 2 == 1 {
                in_text_block = !in_text_block;
            }
            previous_blank = blank && !in_text_block;
        }
        assert!(
            text.ends_with('\n') && !text.ends_with("\n\n"),
            "{path}: a generated file should end with exactly one newline"
        );
    }
}

/// Kinds and capabilities that deliberately have no golden scenario, each
/// with the test that covers them instead.
///
/// A golden target has to be hermetic. `add format` shells out to
/// `spotless:apply` as its last step -- deliberately, so a freshly generated
/// project passes `jails check` -- and whether that succeeds depends on the
/// JDK and the plugin cache of the machine running the suite. A snapshot of
/// that is a snapshot of the toolchain, not of jails.
///
/// An exemption is only allowed to be a pointer, never a hole: the test named
/// here must exist, and the assertion below fails if it is renamed away.
const COVERED_ELSEWHERE: &[(&str, &str)] = &[(
    "format",
    "a_freshly_generated_project_passes_check_with_no_manual_formatting",
)];

/// `{{name}}` is the placeholder syntax because no `{{` appears in any Java
/// jails writes, so a `{{` in generated Java is never content: it is a key the
/// renderer was not given, and it compiles nowhere. The golden corpus is the
/// broadest output jails has, so the check runs over all of it rather than
/// per emitter.
///
/// **Java only, deliberately.** A generated `.http` file uses `{{baseUrl}}` as
/// the HTTP Client format's own variable syntax, a GitHub workflow writes
/// `${{ github.ref }}`, and a compose healthcheck reads `{{.Config.User}}`:
/// the file format's syntax rather than jails', which is the same distinction
/// that keeps those files off `template!`.
#[test]
fn no_generated_java_carries_an_unsubstituted_placeholder() {
    if updating() {
        return;
    }
    let root = golden_root();
    let mut offenders = Vec::new();
    let mut examined = 0;
    for scenario in SCENARIOS {
        for (relative, text) in snapshot(&root.join(scenario.name)) {
            if !relative.ends_with(".java") {
                continue;
            }
            examined += 1;
            if !text.contains("{{") {
                continue;
            }
            let line = text
                .lines()
                .position(|line| line.contains("{{"))
                .map_or(0, |index| index + 1);
            offenders.push(format!("  {}/{relative}:{line}", scenario.name));
        }
    }
    // A scanner that has lost the corpus reports exactly what a clean one
    // does.
    assert!(
        examined > 200,
        "only {examined} generated Java files were examined -- this check has \
         lost the golden corpus and would pass over anything"
    );
    assert!(
        offenders.is_empty(),
        "generated Java carries a template placeholder nothing substituted:\n{}\n\n\
         `{{{{name}}}}` was chosen as the placeholder syntax *because* no `{{{{` \
         appears in any Java jails writes, so one that survives into output is \
         always a key the renderer did not supply. It compiles nowhere and the \
         golden bytes record it as if it were intended.",
        offenders.join("\n")
    );
}

/// Every kind and capability the CLI accepts has a golden scenario.
///
/// The kinds and capabilities are read out of the binary's own help, so a
/// kind added to the enum is a kind this test demands a scenario for on the
/// next run; otherwise a generator can ship with no byte-level verification
/// while the golden count sits still.
#[test]
fn every_kind_and_capability_has_a_golden_scenario() {
    let covered_kinds = common::scenarios::covered_kinds();
    let covered_caps = common::scenarios::covered_capabilities();
    let exempt: Vec<&str> = COVERED_ELSEWHERE.iter().map(|(name, _)| *name).collect();

    let mut missing: Vec<String> = Vec::new();
    for kind in common::scenarios::cli_kinds() {
        if !covered_kinds.contains(kind.as_str()) && !exempt.contains(&kind.as_str()) {
            missing.push(format!("kind `{kind}`"));
        }
    }
    for cap in common::scenarios::cli_capabilities() {
        if !covered_caps.contains(cap.as_str()) && !exempt.contains(&cap.as_str()) {
            missing.push(format!("capability `{cap}`"));
        }
    }

    assert!(
        missing.is_empty(),
        "{} thing(s) jails can generate have no golden scenario:\n  {}\n\n\
         Add a `Scenario` to tests/common/scenarios.rs in the smallest \
         invocation that exercises it, then \
         `UPDATE_GOLDEN=1 cargo test --test golden` and read the diff. \
         If it genuinely cannot be snapshotted -- output that depends on the \
         toolchain rather than on jails -- add it to COVERED_ELSEWHERE with \
         the test that does cover it.",
        missing.len(),
        missing.join("\n  ")
    );

    // Every scenario also has to be reachable: a `SCENARIOS` entry naming a
    // kind clap no longer accepts would fail as a step, but one naming a
    // *capability* that was renamed would quietly stop covering anything.
    let kinds = common::scenarios::cli_kinds();
    let caps = common::scenarios::cli_capabilities();
    for kind in &covered_kinds {
        assert!(
            kinds.contains(*kind),
            "SCENARIOS exercises `g {kind}`, which is not a value `jails generate` accepts \
             -- spell the canonical name, not an alias"
        );
    }
    for cap in &covered_caps {
        assert!(
            caps.contains(*cap),
            "SCENARIOS exercises `add {cap}`, which is not a value `jails add` accepts"
        );
    }

    // Every file under `tests/cli/`, not one, and to any depth -- `model` is a
    // directory of subject files: a reader of one file reports the exemption
    // broken the moment its test moves next door.
    fn read_all(dir: &Path, out: &mut String) {
        for entry in fs::read_dir(dir)
            .unwrap_or_else(|error| panic!("{} is unreadable: {error}", dir.display()))
        {
            let path = entry.expect("failed to read a directory entry").path();
            if path.is_dir() {
                read_all(&path, out);
            } else {
                out.push_str(&fs::read_to_string(&path).unwrap());
            }
        }
    }
    let cli = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/cli");
    let mut cli_tests = String::new();
    read_all(&cli, &mut cli_tests);
    for (name, test) in COVERED_ELSEWHERE {
        assert!(
            cli_tests.contains(test),
            "`{name}` is exempt from the golden suite because `{test}*` under tests/cli/ \
             covers it, but no such test exists any more"
        );
    }
}

/// Every template file is named by some Rust source.
///
/// A template is reached only through `template!`, `template_here!` or
/// `template_at!`, each an `include_str!` of a literal path, so a template no
/// source names by path or basename is a body nothing renders: the generator
/// that rendered it was deleted and its bodies were left behind (S55.1
/// deleted fifty-five of them). The scan is `crates/*/src` and `src`, the
/// production tree; a mention under `tests/` would keep an orphan alive.
#[test]
fn every_template_is_named_by_a_rust_source() {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let mut sources = String::new();
    let mut rust_files = 0usize;
    read_rust_into(&root.join("src"), &mut sources, &mut rust_files);
    for entry in fs::read_dir(root.join("crates")).expect("crates/ is missing") {
        let crate_dir = entry.expect("failed to read a crates/ entry").path();
        read_rust_into(&crate_dir.join("src"), &mut sources, &mut rust_files);
    }
    assert!(
        rust_files >= 200 && sources.len() > 1_000_000,
        "the source scan found {rust_files} .rs files and {} bytes -- it has lost \
         the code, and this gate would pass over an orphaned template",
        sources.len()
    );

    let templates = root.join("templates");
    let mut on_disk = Vec::new();
    collect_files(&templates, &mut on_disk);
    assert!(
        on_disk.len() >= 100,
        "only {} files under templates/ -- the scan has lost the tree",
        on_disk.len()
    );

    let mut orphans = Vec::new();
    for path in on_disk {
        let relative = path
            .strip_prefix(&templates)
            .unwrap()
            .to_str()
            .expect("a template with a non-UTF-8 path")
            .replace('\\', "/");
        let basename = relative.rsplit('/').next().unwrap();
        if !sources.contains(&relative) && !sources.contains(basename) {
            orphans.push(relative);
        }
    }
    orphans.sort();
    assert!(
        orphans.is_empty(),
        "{} template file(s) are named by no Rust source under crates/*/src or src:\n  {}\n\n\
         fix: delete them -- a template nothing renders is a body the generator \
         that used it left behind -- or name it from the emitter that renders it",
        orphans.len(),
        orphans.join("\n  ")
    );
}

/// Every file below `dir`, recursively, in no particular order.
fn collect_files(dir: &Path, out: &mut Vec<PathBuf>) {
    for entry in
        fs::read_dir(dir).unwrap_or_else(|error| panic!("{} is unreadable: {error}", dir.display()))
    {
        let path = entry.expect("failed to read a directory entry").path();
        if path.is_dir() {
            collect_files(&path, out);
        } else {
            out.push(path);
        }
    }
}

/// Every golden directory belongs to a scenario, and every scenario has one.
///
/// A missing golden fails loudly the first time its scenario runs; an orphan
/// sits there looking like coverage, and `git diff tests/golden` -- the review
/// this suite is built on -- shows a clean tree whether or not anything still
/// generates those bytes.
#[test]
fn every_golden_directory_is_a_registered_scenario_and_the_reverse() {
    let registered: std::collections::BTreeSet<&str> =
        SCENARIOS.iter().map(|scenario| scenario.name).collect();
    let root = golden_root();
    let mut on_disk = std::collections::BTreeSet::new();
    for entry in fs::read_dir(&root).expect("tests/golden is missing") {
        let entry = entry.expect("failed to read a tests/golden entry");
        if entry.path().is_dir() {
            on_disk.insert(
                entry
                    .file_name()
                    .to_str()
                    .expect("a golden directory with a non-UTF-8 name")
                    .to_string(),
            );
        }
    }
    let orphans: Vec<&String> = on_disk
        .iter()
        .filter(|name| !registered.contains(name.as_str()))
        .collect();
    assert!(
        orphans.is_empty(),
        "these golden directories belong to no scenario: {orphans:?}\n       \
         fix: register the scenario in tests/common/scenarios.rs, or delete the \
         directory -- a snapshot nothing compares against is not coverage"
    );
    let unsnapshotted: Vec<&&str> = registered
        .iter()
        .filter(|name| !on_disk.contains(**name))
        .collect();
    assert!(
        unsnapshotted.is_empty(),
        "these scenarios have no golden directory: {unsnapshotted:?}\n       \
         fix: UPDATE_GOLDEN=1 cargo test --test golden, then read the diff"
    );
}

/// Every protocol fixture is read by something.
///
/// A fixture nothing decodes proves nothing about compatibility: it is a file
/// that looks like a contract and is not one, and it survives the wire format
/// changing underneath it without a word.
#[test]
fn every_protocol_fixture_is_read_by_something() {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/protocol-golden");
    let mut sources = String::new();
    for area in ["crates", "src", "tests"] {
        read_rust_into(
            &PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(area),
            &mut sources,
            &mut 0,
        );
    }
    assert!(
        sources.len() > 100_000,
        "the source scan found only {} bytes -- it has lost the code, and this \
         gate would pass over an unreferenced fixture",
        sources.len()
    );
    let mut unreferenced = Vec::new();
    for entry in fs::read_dir(&root).expect("tests/protocol-golden is missing") {
        let name = entry
            .expect("failed to read a protocol-golden entry")
            .file_name()
            .to_str()
            .expect("a fixture with a non-UTF-8 name")
            .to_string();
        if !sources.contains(&name) {
            unreferenced.push(name);
        }
    }
    unreferenced.sort();
    assert!(
        unreferenced.is_empty(),
        "these protocol fixtures are read by nothing: {unreferenced:?}\n       \
         fix: assert against the fixture from a test, or delete it -- an \
         unread fixture is a contract nobody checks"
    );
}

/// Every `.rs` file under `dir`, concatenated, counting the files read. For
/// the reference scans above.
fn read_rust_into(dir: &Path, out: &mut String, files: &mut usize) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries {
        let path = entry.expect("failed to read a directory entry").path();
        if path.is_dir() {
            read_rust_into(&path, out, files);
        } else if path.extension().is_some_and(|ext| ext == "rs") {
            *files += 1;
            out.push_str(&without_comments(
                &fs::read_to_string(&path).unwrap_or_default(),
            ));
        }
    }
}

/// Drop `//` comments, so prose cannot satisfy a reference check.
///
/// A scanner that reads its own explanation is the same failure as one that
/// has lost the code: both report exactly what a clean tree reports. A real
/// reference is `include_str!("...")`, which is a string literal; a mention in
/// prose is not a contract.
fn without_comments(source: &str) -> String {
    source
        .lines()
        .map(|line| match line.find("//") {
            Some(at) => &line[..at],
            None => line,
        })
        .collect::<Vec<_>>()
        .join("\n")
}
