//! Byte-level snapshots of everything jails generates.
//!
//! This target exists to make refactoring the generators *safe*. The Java
//! templates are being moved out of Rust `format!` strings and into
//! `templates/`, which is a large mechanical change to code that works, and
//! the only acceptable evidence that such a change is behaviour-preserving is
//! that every generated byte is identical before and after.
//!
//! It is deliberately end-to-end rather than one snapshot per template
//! function: ~20 invocations cover all 80-odd template functions
//! transitively, through the same path a user takes, and a template that is
//! rendered with the wrong arguments is caught as well as one whose text
//! changed.
//!
//! ## Updating
//!
//! ```text
//! UPDATE_GOLDEN=1 cargo test --test golden
//! ```
//!
//! Then **read the diff**. That is the whole point: a change to generated
//! output should be visible and deliberate. `git diff tests/golden` is the
//! review. Regenerating without reading is how a snapshot suite stops being
//! an oracle and starts being a rubber stamp -- which is why the assertions
//! below also check a few semantic properties that a blind regeneration
//! would not fix.

mod common;

use common::scenarios::{Fixture, SCENARIOS, Scenario};
use common::*;
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

fn golden_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/golden")
}

fn updating() -> bool {
    std::env::var_os("UPDATE_GOLDEN").is_some_and(|v| v != "0")
}

/// Every file under `dir`, relative path -> contents, sorted.
///
/// A `BTreeMap` so the comparison is order-independent and the failure names
/// the file rather than a diff of the whole tree.
fn snapshot(dir: &Path) -> BTreeMap<String, String> {
    let mut found = BTreeMap::new();
    collect(dir, dir, &mut found);
    found
}

fn collect(root: &Path, dir: &Path, out: &mut BTreeMap<String, String>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            // `target/` is build output, not something jails generated.
            if path.file_name().is_some_and(|n| n == "target") {
                continue;
            }
            collect(root, &path, out);
            continue;
        }
        let rel = path
            .strip_prefix(root)
            .unwrap()
            .to_string_lossy()
            .replace('\\', "/");
        match fs::read_to_string(&path) {
            Ok(text) => {
                out.insert(rel, text);
            }
            // A binary file would not be jails' output; record its presence
            // so an accidental one is still visible.
            Err(_) => {
                out.insert(rel, "<non-utf8>".to_string());
            }
        }
    }
}

/// What the fixture puts there before jails runs. Subtracted from the
/// snapshot so the goldens hold only what jails itself produced -- otherwise
/// every scenario carries a copy of the fixture pom and the diff on a
/// template change is buried.
fn fixture_files(fixture: Fixture) -> BTreeMap<String, String> {
    let dir = temp_dir("golden-baseline");
    match fixture {
        Fixture::Plain => write_plain_fixture(&dir),
        Fixture::Spring => write_spring_fixture(&dir),
    }
    let files = snapshot(&dir);
    fs::remove_dir_all(&dir).ok();
    files
}

fn run_scenario(scenario: &Scenario) -> BTreeMap<String, String> {
    let root = common::scenarios::prepare(scenario);
    let baseline = fixture_files(scenario.fixture);

    common::scenarios::run_steps(&root, scenario);

    let mut files = snapshot(&root);
    // Keep a file the fixture also had only when jails changed it (pom.xml,
    // application.properties): identical content means jails left it alone.
    files.retain(|path, contents| baseline.get(path) != Some(contents));
    // A seed file is the scenario's input, not jails' output.
    for (rel, _) in scenario.seed {
        files.remove(*rel);
    }
    fs::remove_dir_all(&root).ok();
    files
}

#[test]
fn generated_output_matches_the_golden_snapshots() {
    let root = golden_root();
    let mut mismatches: Vec<String> = Vec::new();

    for scenario in SCENARIOS {
        let produced = run_scenario(scenario);
        let dir = root.join(scenario.name);

        if updating() {
            fs::remove_dir_all(&dir).ok();
            for (rel, contents) in &produced {
                let path = dir.join(rel);
                fs::create_dir_all(path.parent().unwrap()).unwrap();
                fs::write(&path, contents).unwrap();
            }
            continue;
        }

        let expected = snapshot(&dir);
        if expected.is_empty() {
            mismatches.push(format!(
                "scenario `{}` has no golden files -- run `UPDATE_GOLDEN=1 cargo test --test golden`",
                scenario.name
            ));
            continue;
        }
        for (rel, want) in &expected {
            match produced.get(rel) {
                None => mismatches.push(format!("{}/{rel}: no longer generated", scenario.name)),
                Some(got) if got != want => {
                    mismatches.push(format!("{}/{rel}: contents changed", scenario.name))
                }
                Some(_) => {}
            }
        }
        for rel in produced.keys() {
            if !expected.contains_key(rel) {
                mismatches.push(format!("{}/{rel}: newly generated", scenario.name));
            }
        }
    }

    assert!(
        mismatches.is_empty(),
        "generated output changed in {} place(s):\n  {}\n\n\
         If the change is intended: UPDATE_GOLDEN=1 cargo test --test golden, \
         then read `git diff tests/golden` before committing.",
        mismatches.len(),
        mismatches.join("\n  ")
    );
}

/// A snapshot suite that is only ever regenerated stops being an oracle. These
/// are properties a blind `UPDATE_GOLDEN=1` would not restore, so they fail
/// loudly rather than absorbing a regression into the new baseline.
#[test]
fn the_goldens_still_hold_the_properties_that_matter() {
    if updating() {
        return;
    }
    let root = golden_root();
    let all: Vec<(String, String)> = SCENARIOS
        .iter()
        .flat_map(|s| {
            snapshot(&root.join(s.name))
                .into_iter()
                .map(move |(rel, text)| (format!("{}/{rel}", s.name), text))
        })
        .collect();
    assert!(!all.is_empty(), "no goldens recorded yet");

    for (path, text) in &all {
        if !path.ends_with(".java") {
            continue;
        }
        // `{{` is `format!`'s escape for a literal brace and must never
        // survive into output. `}}` is *not* checkable the same way: it
        // occurs legitimately in Javadoc, where a JSON example inside
        // `{@code ...}` ends `...}}`. One-sided is the honest check.
        assert!(
            !text.contains("{{"),
            "{path}: generated Java contains an unexpanded escaped brace"
        );
        // An unsubstituted placeholder is the failure mode of moving
        // templates out to files, and it compiles nowhere.
        for marker in ["{name}", "{pkg}", "{Name}", "{package}"] {
            assert!(
                !text.contains(marker),
                "{path}: unsubstituted placeholder `{marker}`"
            );
        }
        assert!(
            text.starts_with("package ") || text.starts_with("/**"),
            "{path}: a generated Java file should start with its package or Javadoc"
        );
        // palantir-java-format removes both of these, so leaving one in means
        // `add format` -- which jails installs itself -- fails `jails check`
        // on a project whose every line jails wrote. `tidy_blank_lines` is
        // the write-path rule; this is what keeps a new template honest.
        // A blank line inside a text block is data, and is left alone.
        let mut in_text_block = false;
        let mut previous_blank = false;
        for (number, line) in text.lines().enumerate() {
            let blank = line.trim().is_empty();
            assert!(
                !(blank && previous_blank),
                "{path}:{}: two blank lines in a row -- palantir-java-format removes one",
                number + 1
            );
            if line.matches("\"\"\"").count() % 2 == 1 {
                in_text_block = !in_text_block;
            }
            previous_blank = blank && !in_text_block;
        }
        assert!(
            text.ends_with('\n') && !text.ends_with("\n\n"),
            "{path}: a generated file should end with exactly one newline"
        );
    }
}

/// Kinds and capabilities that deliberately have no golden scenario, each
/// with the test that covers them instead.
///
/// A golden target has to be hermetic. `add format` shells out to
/// `spotless:apply` as its last step -- deliberately, so a freshly generated
/// project passes `jails check` -- and whether that succeeds depends on the
/// JDK and the plugin cache of the machine running the suite. A snapshot of
/// that is a snapshot of the toolchain, not of jails.
///
/// An exemption is only allowed to be a pointer, never a hole: the test named
/// here must exist, and the assertion below fails if it is renamed away.
const COVERED_ELSEWHERE: &[(&str, &str)] = &[(
    "format",
    "a_freshly_generated_project_passes_check_with_no_manual_formatting",
)];

/// The header of this file claims *"every artifact kind and every capability,
/// in the smallest invocation that exercises it."* That comment was false by
/// twelve when `plan.md` §8.5 counted: eight kinds were added and the golden
/// count never moved off 162 files / 25 scenarios, so the most complex
/// generators in the tree -- a leased store, an outbox, a traversal engine --
/// had no byte-level verification at all.
///
/// This is the test that makes the claim true and keeps it true. It reads the
/// kinds and capabilities out of the binary's own help, so a kind added to the
/// enum is a kind this test demands a scenario for on the next run.
#[test]
fn every_kind_and_capability_has_a_golden_scenario() {
    let covered_kinds = common::scenarios::covered_kinds();
    let covered_caps = common::scenarios::covered_capabilities();
    let exempt: Vec<&str> = COVERED_ELSEWHERE.iter().map(|(name, _)| *name).collect();

    let mut missing: Vec<String> = Vec::new();
    for kind in common::scenarios::cli_kinds() {
        if !covered_kinds.contains(kind.as_str()) && !exempt.contains(&kind.as_str()) {
            missing.push(format!("kind `{kind}`"));
        }
    }
    for cap in common::scenarios::cli_capabilities() {
        if !covered_caps.contains(cap.as_str()) && !exempt.contains(&cap.as_str()) {
            missing.push(format!("capability `{cap}`"));
        }
    }

    assert!(
        missing.is_empty(),
        "{} thing(s) jails can generate have no golden scenario:\n  {}\n\n\
         Add a `Scenario` to tests/common/scenarios.rs in the smallest \
         invocation that exercises it, then \
         `UPDATE_GOLDEN=1 cargo test --test golden` and read the diff. \
         If it genuinely cannot be snapshotted -- output that depends on the \
         toolchain rather than on jails -- add it to COVERED_ELSEWHERE with \
         the test that does cover it.",
        missing.len(),
        missing.join("\n  ")
    );

    // Every scenario also has to be reachable: a `SCENARIOS` entry naming a
    // kind clap no longer accepts would fail as a step, but one naming a
    // *capability* that was renamed would quietly stop covering anything.
    let kinds = common::scenarios::cli_kinds();
    let caps = common::scenarios::cli_capabilities();
    for kind in &covered_kinds {
        assert!(
            kinds.contains(*kind),
            "SCENARIOS exercises `g {kind}`, which is not a value `jails generate` accepts \
             -- spell the canonical name, not an alias"
        );
    }
    for cap in &covered_caps {
        assert!(
            caps.contains(*cap),
            "SCENARIOS exercises `add {cap}`, which is not a value `jails add` accepts"
        );
    }

    let cli_tests =
        fs::read_to_string(Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/cli.rs")).unwrap();
    for (name, test) in COVERED_ELSEWHERE {
        assert!(
            cli_tests.contains(test),
            "`{name}` is exempt from the golden suite because `{test}*` in tests/cli.rs covers \
             it, but no such test exists any more"
        );
    }
}
