// Generated by jails from art_ent_note_dto_request. Clean hand edits survive regeneration.
package com.example.demo.web;

import com.example.demo.domain.Note;
import com.example.demo.domain.TimeOrderedUuid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.time.Instant;

public record NoteRequest(
    @NotBlank String title,
    @NotNull Instant createdAt
) {

    /**
     * The domain row this request describes, with every server-assigned
     * value supplied here rather than taken from the caller.
     */
    public Note toDomain() {
        return new Note(
                TimeOrderedUuid.next(),
                title,
                createdAt);
    }
}
