// Generated by jails from art_ent_ticket_record. Clean hand edits survive regeneration.
package com.example.demo.domain;

import java.util.Objects;
import java.util.Optional;

public record Ticket(
    long id,
    String subject,
    Optional<String> status
) {

    public Ticket {
        Objects.requireNonNull(subject, "subject");
        subject = subject.trim();
        if (subject.isEmpty()) {
            throw new IllegalArgumentException("subject must not be blank");
        }
        status = Objects.requireNonNullElse(status, Optional.empty());
    }
}
