// Generated by jails from art_cmp_strategy_eligibility_impl_domestic. Clean hand edits survive regeneration.
package com.example.demo.service;

import com.example.demo.domain.Eligibility;
import com.example.demo.domain.Transaction;

public final class DomesticEligibility implements Eligibility {

    @Override
    public boolean appliesTo(Transaction value) {
        return false;
    }

    // Reader-owned implementation methods belong below this stable boundary.
}
