// Generated by jails from art_ent_article_search. Clean hand edits survive regeneration.
package com.example.demo.ports.search;

import com.example.demo.domain.Article;
import java.util.List;

public interface ArticleSearch {

    /**
     * @param query what the reader typed. It is parsed by PostgreSQL, not
     *     concatenated into SQL -- see the adapter.
     * @param limit how many rows at most.
     */
    List<Article> matching(String query, int limit);
}
