// Generated by jails from art_cap_db_ent_ticket_repository_it. Clean hand edits survive regeneration.
package com.example.demo.adapters.jdbc;

import com.example.demo.TestcontainersConfig;
import com.example.demo.domain.Ticket;
import com.example.demo.repository.TicketRepository;
import com.example.demo.repository.TicketRepositoryContract;
import java.util.Optional;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Import;
import org.springframework.transaction.annotation.Transactional;

@Import(TestcontainersConfig.class)
@SpringBootTest
@Transactional
class JdbcTicketRepositoryIT {

    @Autowired
    private TicketRepository repository;

    @Test
    void satisfiesTheTicketRepositoryContractAgainstTheRealDatabase() {
        TicketRepositoryContract.savesReadsAndDeletes(
                repository, new Ticket(1L, "sample", Optional.empty()));
    }

    // Reader-owned cases belong below this stable boundary.
}
