// Generated by jails from art_op_tickets_by_status_query_it. Clean hand edits survive regeneration.
package com.example.demo.adapters.jdbc;

import static org.assertj.core.api.Assertions.assertThat;

import com.example.demo.TestcontainersConfig;
import com.example.demo.application.queries.TicketsByStatusQuery;
import com.example.demo.domain.Ticket;
import com.example.demo.repository.TicketRepository;
import java.util.Optional;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Import;
import org.springframework.transaction.annotation.Transactional;

@Import(TestcontainersConfig.class)
@SpringBootTest
@Transactional
class JdbcTicketsByStatusQueryIT {

    @Autowired
    private TicketRepository repository;

    @Autowired
    private TicketsByStatusQuery query;

    @Test
    void answersFromTheRealDatabase() {
        // The *stored* row, not the argument: with a database-assigned key
        // the two differ by exactly the column the query reads back.
        Ticket stored = repository.save(new Ticket(1L, "sample", Optional.empty()));

        var found = query.execute(new TicketsByStatusQuery.Input("sample", Optional.empty()));

        assertThat(found).contains(stored);
    }

    // Reader-owned cases belong below this stable boundary.
}
