// Generated by jails from art_ent_payout_repository_memory. Clean hand edits survive regeneration.
package com.example.demo.adapters.memory;

import com.example.demo.domain.Payout;
import com.example.demo.repository.PayoutRepository;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;
import org.springframework.stereotype.Component;

@Component
public final class InMemoryPayoutRepository implements PayoutRepository {

    private final Map<UUID, Payout> rows = new LinkedHashMap<>();

    @Override
    public Optional<Payout> findById(UUID id) {
        return Optional.ofNullable(rows.get(id));
    }

    @Override
    public List<Payout> findAll() {
        return List.copyOf(rows.values());
    }

    @Override
    public Payout save(Payout value) {
        rows.put(value.id(), value);
        return value;
    }

    @Override
    public boolean deleteById(UUID id) {
        return rows.remove(id) != null;
    }
}
