-- Generated by jails from the accepted model.
create table owners (
    id uuid not null primary key,
    name text not null check (length(btrim(name)) > 0),
    created_at timestamptz default current_timestamp not null
);
