-- Generated by jails from the accepted semantic schema.
create table items (
    id uuid not null primary key,
    owner_id uuid not null,
    name text not null check (length(btrim(name)) > 0),
    created_at timestamptz default current_timestamp not null
);
create index idx_items_owner_id on items (owner_id);
