-- Generated by jails from the accepted semantic schema.
alter table items
  add constraint fk_items_item_owner
  foreign key (owner_id) references owners (id)
  on delete restrict on update restrict;
