-- Generated by jails from the accepted semantic schema.
alter table articles
    add column search_vector tsvector
    generated always as (to_tsvector('english', coalesce(title, '') || ' ' || coalesce(body, ''))) stored;
create index articles_search_vector_idx on articles using gin (search_vector);
