// Generated by jails from art_ent_item_dto_request. Clean hand edits survive regeneration.
package com.example.demo.web;

import com.example.demo.domain.Item;
import com.example.demo.domain.TimeOrderedUuid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.time.Instant;
import java.util.UUID;

public record ItemRequest(
    @NotNull UUID ownerId,
    @NotBlank String name
) {

    /**
     * The domain row this request describes, with every server-assigned
     * value supplied here rather than taken from the caller.
     */
    public Item toDomain() {
        return new Item(
                TimeOrderedUuid.next(),
                ownerId,
                name,
                Instant.now());
    }
}
