// Generated by jails from art_ent_item_http_controller. Clean hand edits survive regeneration.
package com.example.demo.web;

import com.example.demo.domain.Item;
import com.example.demo.service.ItemService;
import jakarta.validation.Valid;
import java.net.URI;
import java.util.List;
import java.util.UUID;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping(ItemController.PATH)
public final class ItemController {

    /** The collection this controller serves. */
    public static final String PATH = "/items";

    private final ItemService service;

    public ItemController(ItemService service) {
        this.service = service;
    }

    @GetMapping
    public List<Item> list() {
        return service.all();
    }

    /** 404 rather than an empty 200: "no such thing" and "here is nothing" differ. */
    @GetMapping("/{id}")
    public ResponseEntity<Item> byId(@PathVariable("id") UUID id) {
        return service.byId(id)
                .map(ResponseEntity::ok)
                .orElseGet(() -> ResponseEntity.notFound().build());
    }

    /**
     * The request record, not the domain row: a caller supplies what
     * they are asked for, and every server-assigned value is minted by
     * {@link ItemRequest#toDomain()} rather than taken from the body.
     */
    @PostMapping
    public ResponseEntity<Item> create(@Valid @RequestBody ItemRequest request) {
        Item created = service.save(request.toDomain());
        return ResponseEntity.created(URI.create(PATH + "/" + created.id()))
                .body(created);
    }

    /** 204 when something was removed, 404 when there was nothing to remove. */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable("id") UUID id) {
        return service.delete(id)
                ? ResponseEntity.noContent().build()
                : ResponseEntity.notFound().build();
    }

    // Reader-owned controller methods belong below this stable boundary.
}
