// Generated by jails from art_ent_owner_dto_response. Clean hand edits survive regeneration.
package com.example.demo.web;

import com.example.demo.domain.Owner;
import java.time.Instant;
import java.util.UUID;

public record OwnerResponse(
    UUID id,
    String name,
    Instant createdAt
) {

    public static OwnerResponse fromDomain(Owner owner) {
        return new OwnerResponse(
                owner.id(),
                owner.name(),
                owner.createdAt());
    }
}
