//! Standalone main and test source-unit backend.

use crate::CompileError;
use jails_contracts::{FileKind, FileMode, ProjectPath, Provenance, RenderedFile, RenderedTree};
use jails_model::{AppModel, SourceUnit, StableId, UnitKind};
use std::collections::BTreeSet;

const JAVA_MAIN_ROOT: &str = ".jails/generated/main/java";
const JAVA_TEST_ROOT: &str = ".jails/generated/test/java";

pub(crate) fn lower_and_emit(
    model: &AppModel,
    output: &mut RenderedTree,
    spring_boot: bool,
) -> Result<(), CompileError> {
    for source in model.units.values() {
        for unit in lower(source, model, spring_boot)? {
            output
                .insert(unit.path, unit.file)
                .map_err(CompileError::new)?;
        }
    }
    Ok(())
}

struct Unit {
    path: ProjectPath,
    file: RenderedFile,
}

/// **A unit's package is projected here, not read off the unit.**
///
/// `SourceUnit::java_package` is written by the linker, which runs before the
/// project's `[layout]` is on the model -- so it always spells the default.
/// Reading it put a sealed type in `domain` on a project whose records had
/// already moved to `core`: two packages for one layer, in one tree, and
/// nothing to report it. `audit.md` A3.11b.
///
/// So the *layer* travels on the unit and the name is computed with the
/// layout, which is what `package_for` is for. A unit whose package the reader
/// named carries no layer, and keeps the name they gave it -- they said where
/// it goes, so a rename of that layer is not about them.
fn lower(
    source: &SourceUnit,
    model: &AppModel,
    spring_boot: bool,
) -> Result<Vec<Unit>, CompileError> {
    let id = source.id.as_str();
    let package = &placed(source, model);
    let type_name = &source.java_type;
    if matches!(source.kind, UnitKind::Test | UnitKind::IntegrationTest) {
        let artifact = format!("art_{id}_test");
        let rendered = format!(
            "// Generated by jails from {artifact}. Clean hand edits survive regeneration.\npackage {package};\n\n{}\n",
            standalone_test_body(source.kind, type_name)
        );
        return Ok(vec![file(
            JAVA_TEST_ROOT,
            package,
            type_name,
            FileKind::JavaTest,
            rendered,
            artifact,
            true,
            id,
        )?]);
    }
    if source.kind == UnitKind::Strategy {
        return lower_strategy(source, model, spring_boot);
    }
    if source.kind == UnitKind::Controller {
        return lower_controller(source, model);
    }
    let main_body = match source.kind {
        UnitKind::Class => format!("public final class {type_name} {{\n}}"),
        UnitKind::Interface => format!("public interface {type_name} {{\n}}"),
        UnitKind::Service => format!("@Component\nclass {type_name} {{\n}}"),
        UnitKind::Sealed => sealed_body(type_name, &source.variants),
        UnitKind::Test | UnitKind::IntegrationTest | UnitKind::Strategy | UnitKind::Controller => {
            unreachable!()
        }
    };
    let main_imports = match source.kind {
        UnitKind::Service => {
            BTreeSet::from(["org.springframework.stereotype.Component".to_string()])
        }
        UnitKind::Class | UnitKind::Interface | UnitKind::Sealed => BTreeSet::new(),
        UnitKind::Test | UnitKind::IntegrationTest | UnitKind::Strategy | UnitKind::Controller => {
            unreachable!()
        }
    };
    let main_artifact = format!("art_{id}_main");
    let mut units = vec![file(
        JAVA_MAIN_ROOT,
        package,
        type_name,
        FileKind::JavaMain,
        crate::emit_java::render(package, &main_imports, &main_body, &main_artifact),
        main_artifact,
        !matches!(source.kind, UnitKind::Interface | UnitKind::Sealed),
        id,
    )?];
    if let Some(test_body) = test_body(source, type_name) {
        let test_artifact = format!("art_{id}_test");
        let rendered = format!(
            "// Generated by jails from {test_artifact}. Clean hand edits survive regeneration.\npackage {package};\n\n{test_body}\n"
        );
        units.push(file(
            JAVA_TEST_ROOT,
            package,
            &format!("{type_name}Test"),
            FileKind::JavaTest,
            rendered,
            test_artifact,
            true,
            id,
        )?);
    }
    Ok(units)
}

fn test_body(source: &SourceUnit, type_name: &str) -> Option<String> {
    match source.kind {
        UnitKind::Interface => None,
        UnitKind::Class => {
            let variable = lower_first(type_name);
            Some(format!(
                "import org.junit.jupiter.api.Disabled;\nimport org.junit.jupiter.api.Test;\n\nclass {type_name}Test {{\n\n    @Test\n    @Disabled(\"todo: state what {type_name} is supposed to do, then assert it\")\n    void todo() {{\n        {type_name} {variable} = new {type_name}();\n\n        // Replace this with the behaviour {type_name} exists for. Asserting that\n        // it is not null would pass while the class is entirely broken.\n    }}\n}}"
            ))
        }
        UnitKind::Service => Some(format!(
            "import org.junit.jupiter.api.Test;\n\nimport static org.junit.jupiter.api.Assertions.assertNotNull;\n\nclass {type_name}Test {{\n\n    @Test\n    void instantiates() {{\n        assertNotNull(new {type_name}());\n    }}\n}}"
        )),
        UnitKind::Sealed => Some(sealed_test_body(type_name, &source.variants)),
        UnitKind::Test | UnitKind::IntegrationTest | UnitKind::Strategy | UnitKind::Controller => {
            None
        }
    }
}

fn sealed_body(type_name: &str, variants: &[String]) -> String {
    let permits = variants
        .iter()
        .map(|variant| format!("{type_name}.{variant}"))
        .collect::<Vec<_>>()
        .join(", ");
    let records = variants
        .iter()
        .map(|variant| {
            format!(
                "    /** TODO: give {variant} the components it carries. */\n    record {variant}() implements {type_name} {{}}"
            )
        })
        .collect::<Vec<_>>()
        .join("\n\n");
    format!("public sealed interface {type_name} permits {permits} {{\n\n{records}\n}}")
}

fn sealed_test_body(type_name: &str, variants: &[String]) -> String {
    let arms = variants
        .iter()
        .map(|variant| {
            format!(
                "            case {type_name}.{variant} ignored -> \"{}\";",
                variant.to_ascii_lowercase()
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    let tests = variants
        .iter()
        .map(|variant| {
            format!(
                "    @Test\n    void describes{variant}() {{\n        assertEquals(\"{}\", describe(new {type_name}.{variant}()));\n    }}",
                variant.to_ascii_lowercase()
            )
        })
        .collect::<Vec<_>>()
        .join("\n\n");
    format!(
        "import org.junit.jupiter.api.Test;\n\nimport static org.junit.jupiter.api.Assertions.assertEquals;\n\nclass {type_name}Test {{\n\n    private String describe({type_name} value) {{\n        return switch (value) {{\n{arms}\n        }};\n    }}\n\n{tests}\n}}"
    )
}

fn standalone_test_body(kind: UnitKind, type_name: &str) -> String {
    match kind {
        UnitKind::Test => format!(
            "import org.junit.jupiter.api.Test;\n\nimport static org.junit.jupiter.api.Assertions.assertTrue;\n\nclass {type_name} {{\n\n    @Test\n    void shouldDoSomething() {{\n        assertTrue(true);\n    }}\n\n}}"
        ),
        UnitKind::IntegrationTest => format!(
            "import org.junit.jupiter.api.Disabled;\nimport org.junit.jupiter.api.Test;\n\n@Disabled(\"todo: wire the real integration boundary\")\nclass {type_name} {{\n\n    @Test\n    void worksEndToEnd() {{\n        throw new UnsupportedOperationException(\"todo\");\n    }}\n}}"
        ),
        UnitKind::Class
        | UnitKind::Interface
        | UnitKind::Service
        | UnitKind::Sealed
        | UnitKind::Strategy
        | UnitKind::Controller => {
            unreachable!()
        }
    }
}

/// **A strategy is the one Spring-shaped unit a plain project also gets.**
///
/// `@Component` on each implementation is how Spring collects them into the
/// evaluator's `List<Port>`; without Spring the reader passes the list to the
/// constructor themselves, which the evaluator already accepts. Nothing else
/// about the shape changes, so `CLAUDE.md`'s rule holds -- "plain-Maven
/// projects get the same layout with no annotation, because one placement is
/// easier to explain than one that depends on the build file".
///
/// `refuse.rs` used to group `Strategy` with `Service` and `Controller` and
/// reject all three without Spring. That is right for the other two, whose
/// whole body is an annotation, and wrong here: it made `g strategy` refuse on
/// exactly the plain projects the legacy generator has always supported.
fn lower_strategy(
    source: &SourceUnit,
    model: &AppModel,
    spring_boot: bool,
) -> Result<Vec<Unit>, CompileError> {
    let id = source.id.as_str();
    let domain = &placed(source, model);
    // Compared against the *projection*, so a project that renames `domain`
    // to `core` is asked for `core` rather than refused for not saying
    // `domain`. The rule is unchanged -- a strategy's port belongs in the
    // domain layer, because `g scaffold` writes an ArchUnit rule forbidding
    // Spring inside it -- and only its spelling now follows the reader's.
    if domain != &model.project.package_for(jails_model::Package::Domain) {
        return Err(CompileError::new(format!(
            "strategy `{}` must use the canonical domain package",
            source.java_type
        )));
    }
    let base = domain.strip_suffix(".domain").ok_or_else(|| {
        CompileError::new(format!(
            "strategy `{}` must use the canonical domain package",
            source.java_type
        ))
    })?;
    let service = format!("{base}.service");
    let name = &source.java_type;
    let on = source
        .on
        .as_deref()
        .ok_or_else(|| CompileError::new(format!("strategy `{name}` has no input Java type")))?;
    let (return_type, method, empty) = match source.yields.as_deref() {
        Some(yields) => (
            format!("Optional<{yields}>"),
            "evaluate",
            "Optional.empty()",
        ),
        None => ("boolean".to_string(), "appliesTo", "false"),
    };

    let abi_artifact = format!("art_{id}_abi");
    let abi_imports = source
        .yields
        .as_ref()
        .map(|_| BTreeSet::from(["java.util.Optional".to_string()]))
        .unwrap_or_default();
    let abi_body = format!(
        "public interface {name} {{\n\n    {return_type} {method}({on} value);\n\n    // Reader-owned ABI extensions belong below this stable boundary.\n}}"
    );
    let mut units = vec![file(
        JAVA_MAIN_ROOT,
        domain,
        name,
        FileKind::JavaMain,
        crate::emit_java::render(domain, &abi_imports, &abi_body, &abi_artifact),
        abi_artifact,
        false,
        id,
    )?];

    let evaluator_artifact = format!("art_{id}_evaluator");
    let mut evaluator_imports = BTreeSet::from([
        "java.util.List".to_string(),
        format!("{domain}.{name}"),
        format!("{domain}.{on}"),
    ]);
    if spring_boot {
        evaluator_imports.insert("org.springframework.stereotype.Component".to_string());
    }
    if let Some(yields) = source.yields.as_deref() {
        evaluator_imports.insert("java.util.Optional".to_string());
        evaluator_imports.insert(format!("{domain}.{yields}"));
    }
    let plural = format!("{}s", lower_first(name));
    let evaluation = if source.yields.is_some() {
        format!(
            "return {plural}.stream().flatMap(strategy -> strategy.{method}(value).stream()).findFirst();"
        )
    } else {
        format!("return {plural}.stream().anyMatch(strategy -> strategy.{method}(value));")
    };
    let evaluator = format!("{name}Evaluator");
    let bean = match spring_boot {
        true => "@Component\n",
        false => "",
    };
    let evaluator_body = format!(
        "{bean}public final class {evaluator} {{\n\n    private final List<{name}> {plural};\n\n    public {evaluator}(List<{name}> {plural}) {{\n        this.{plural} = List.copyOf({plural});\n    }}\n\n    public {return_type} {method}({on} value) {{\n        {evaluation}\n    }}\n\n    // Reader-owned evaluator methods belong below this stable boundary.\n}}"
    );
    units.push(file(
        JAVA_MAIN_ROOT,
        &service,
        &evaluator,
        FileKind::JavaMain,
        crate::emit_java::render(
            &service,
            &evaluator_imports,
            &evaluator_body,
            &evaluator_artifact,
        ),
        evaluator_artifact,
        true,
        id,
    )?);

    for (position, variant) in source.variants.iter().enumerate() {
        let implementation = format!("{variant}{name}");
        let variant_id = lower_first(variant);
        let implementation_artifact = format!("art_{id}_impl_{variant_id}");
        let mut imports = BTreeSet::from([format!("{domain}.{name}"), format!("{domain}.{on}")]);
        if spring_boot {
            imports.insert("org.springframework.core.annotation.Order".to_string());
            imports.insert("org.springframework.stereotype.Component".to_string());
        }
        if let Some(yields) = source.yields.as_deref() {
            imports.insert("java.util.Optional".to_string());
            imports.insert(format!("{domain}.{yields}"));
        }
        // Order is only expressible as an annotation, so without Spring the
        // list arrives in the order the reader passes it -- which the
        // evaluator's Javadoc already says decides the answer.
        let ordering = match spring_boot {
            true => format!("@Component\n@Order({})\n", position + 1),
            false => String::new(),
        };
        let implementation_body = format!(
            "{ordering}public final class {implementation} implements {name} {{\n\n    @Override\n    public {return_type} {method}({on} value) {{\n        return {empty};\n    }}\n\n    // Reader-owned implementation methods belong below this stable boundary.\n}}"
        );
        units.push(file(
            JAVA_MAIN_ROOT,
            &service,
            &implementation,
            FileKind::JavaMain,
            crate::emit_java::render(
                &service,
                &imports,
                &implementation_body,
                &implementation_artifact,
            ),
            implementation_artifact,
            true,
            id,
        )?);

        let test_artifact = format!("art_{id}_test_{variant_id}");
        let assertion = if source.yields.is_some() {
            format!("assertTrue(new {implementation}().{method}(null).isEmpty());")
        } else {
            format!("assertFalse(new {implementation}().{method}(null));")
        };
        let assertion_import = if source.yields.is_some() {
            "org.junit.jupiter.api.Assertions.assertTrue"
        } else {
            "org.junit.jupiter.api.Assertions.assertFalse"
        };
        let test_body = format!(
            "import org.junit.jupiter.api.Test;\n\nimport static {assertion_import};\n\nclass {implementation}Test {{\n\n    @Test\n    void startsWithNoMatch() {{\n        {assertion}\n    }}\n\n    // Reader-owned tests belong below this stable boundary.\n}}"
        );
        units.push(file(
            JAVA_TEST_ROOT,
            &service,
            &format!("{implementation}Test"),
            FileKind::JavaTest,
            format!(
                "// Generated by jails from {test_artifact}. Clean hand edits survive regeneration.\npackage {service};\n\n{test_body}\n"
            ),
            test_artifact,
            true,
            id,
        )?);
    }
    Ok(units)
}

fn lower_controller(source: &SourceUnit, model: &AppModel) -> Result<Vec<Unit>, CompileError> {
    let endpoint = source.endpoint.as_ref().ok_or_else(|| {
        CompileError::new(format!(
            "controller `{}` has no HTTP endpoint",
            source.java_type
        ))
    })?;
    let id = source.id.as_str();
    let package = &placed(source, model);
    let type_name = &source.java_type;
    let stem = type_name.strip_suffix("Controller").unwrap_or(type_name);
    let domain = model.project.package_for(jails_model::Package::Domain);
    let mapping = match endpoint.method {
        jails_model::EndpointMethod::Get => "GetMapping",
        jails_model::EndpointMethod::Post => "PostMapping",
        jails_model::EndpointMethod::Put => "PutMapping",
        jails_model::EndpointMethod::Patch => "PatchMapping",
        jails_model::EndpointMethod::Delete => "DeleteMapping",
    };
    let handler = match endpoint.method {
        jails_model::EndpointMethod::Get => "get",
        jails_model::EndpointMethod::Post => "post",
        jails_model::EndpointMethod::Put => "put",
        jails_model::EndpointMethod::Patch => "patch",
        jails_model::EndpointMethod::Delete => "delete",
    };
    let mut imports = BTreeSet::from([
        "org.springframework.web.bind.annotation.RestController".to_string(),
        format!("org.springframework.web.bind.annotation.{mapping}"),
    ]);
    let parameter = match endpoint.accepts.as_deref() {
        Some(request) => {
            let binding = match endpoint.consumes {
                jails_model::RequestFormat::Json => "RequestBody",
                jails_model::RequestFormat::Form => "ModelAttribute",
            };
            imports.insert(format!("org.springframework.web.bind.annotation.{binding}"));
            imports.insert(format!("{domain}.{request}"));
            format!("@{binding} {request} request")
        }
        None => String::new(),
    };
    let (return_type, body) = match endpoint.returns.as_deref() {
        Some(response) => {
            imports.insert(format!("{domain}.{response}"));
            (
                response.to_string(),
                format!(
                    "throw new UnsupportedOperationException(\"todo: build the {response} this route returns\");"
                ),
            )
        }
        None => ("String".to_string(), format!("return \"{stem}\";")),
    };
    let consumes = match (endpoint.accepts.as_ref(), endpoint.consumes) {
        (Some(_), jails_model::RequestFormat::Json) => {
            imports.insert("org.springframework.http.MediaType".to_string());
            ", consumes = MediaType.APPLICATION_JSON_VALUE"
        }
        (Some(_), jails_model::RequestFormat::Form) => {
            imports.insert("org.springframework.http.MediaType".to_string());
            ", consumes = MediaType.APPLICATION_FORM_URLENCODED_VALUE"
        }
        (None, _) => "",
    };
    let ejection_id = format!("art_{id}_http");
    let controller_artifact = format!("{ejection_id}_controller");
    let controller_body = format!(
        "@RestController\npublic final class {type_name} {{\n\n    @{mapping}(path = \"{}\"{consumes})\n    public {return_type} {handler}({parameter}) {{\n        {body}\n    }}\n\n    // Reader-owned controller methods belong below this stable boundary.\n}}",
        endpoint.path
    );
    let mut controller = file(
        JAVA_MAIN_ROOT,
        package,
        type_name,
        FileKind::JavaMain,
        crate::emit_java::render(package, &imports, &controller_body, &controller_artifact),
        controller_artifact,
        true,
        id,
    )?;
    controller.file.provenance.ejection_id = Some(ejection_id.clone());

    let parameter_types = endpoint
        .accepts
        .as_ref()
        .map(|request| format!(", {request}.class"))
        .unwrap_or_default();
    let mut test_imports = BTreeSet::from([
        "org.junit.jupiter.api.Test".to_string(),
        "static org.junit.jupiter.api.Assertions.assertEquals".to_string(),
        format!("org.springframework.web.bind.annotation.{mapping}"),
    ]);
    if let Some(request) = endpoint.accepts.as_ref() {
        test_imports.insert(format!("{domain}.{request}"));
    }
    let test_body = format!(
        "class {stem}ControllerTest {{\n\n    @Test\n    void exposesTheDeclaredRoute() throws Exception {{\n        var handler = {type_name}.class.getDeclaredMethod(\"{handler}\"{parameter_types});\n        var mapping = handler.getAnnotation({mapping}.class);\n        assertEquals(\"{}\", mapping.path()[0]);\n    }}\n\n    // Reader-owned tests belong below this stable boundary.\n}}",
        endpoint.path
    );
    let test_artifact = format!("{ejection_id}_test");
    let mut test = file(
        JAVA_TEST_ROOT,
        package,
        &format!("{stem}ControllerTest"),
        FileKind::JavaTest,
        crate::emit_java::render(package, &test_imports, &test_body, &test_artifact),
        test_artifact,
        true,
        id,
    )?;
    test.file.provenance.ejection_id = Some(ejection_id);
    Ok(vec![controller, test])
}

#[allow(clippy::too_many_arguments)]
fn file(
    root: &str,
    package: &str,
    type_name: &str,
    kind: FileKind,
    rendered: String,
    artifact_id: String,
    ejectable: bool,
    semantic_id: &str,
) -> Result<Unit, CompileError> {
    let package_path = package.replace('.', "/");
    let path = ProjectPath::parse(format!("{root}/{package_path}/{type_name}.java"))
        .map_err(CompileError::new)?;
    Ok(Unit {
        path,
        file: RenderedFile {
            kind,
            mode: FileMode::Regular,
            bytes: rendered.into_bytes(),
            provenance: Provenance {
                artifact_id,
                ejection_id: None,
                ejectable,
                semantic_ids: BTreeSet::from([semantic_id.to_string()]),
                compiler_pass: "java-source-units".to_string(),
            },
        },
    })
}

fn lower_first(value: &str) -> String {
    let mut characters = value.chars();
    characters.next().map_or_else(String::new, |first| {
        first.to_ascii_lowercase().to_string() + characters.as_str()
    })
}

/// Where this unit's Java goes, with the project's layout applied.
///
/// A derived placement is a *layer*, so it is renamed with every other
/// artifact in that layer. A package the reader named is theirs, and is used
/// exactly as written -- which is why this is not simply `package_for` on a
/// layer the linker always supplies.
fn placed(source: &SourceUnit, model: &AppModel) -> String {
    source.layer.map_or_else(
        || source.java_package.clone(),
        |layer| model.project.package_for(layer),
    )
}
