// Generated by jails from art_ent_issue_priority_test. Clean hand edits survive regeneration.
package com.example.demo.domain;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

import org.junit.jupiter.api.Test;

class IssuePriorityTest {

    @Test
    void parsesItsOwnNames() {
        assertEquals(IssuePriority.NONE, IssuePriority.valueOf("NONE"));
    }

    /** The failure mode worth pinning: valueOf throws, it does not return null. */
    @Test
    void rejectsAnUnknownName() {
        assertThrows(IllegalArgumentException.class, () -> IssuePriority.valueOf("NOPE"));
    }

    @Test
    void declaresEveryConstantExactlyOnce() {
        assertEquals(3, IssuePriority.values().length);
    }

    @Test
    void roundTripsEveryWireValue() {
        assertEquals("-", IssuePriority.NONE.wire());
        assertEquals(IssuePriority.NONE, IssuePriority.fromWire("-"));
        assertEquals("!", IssuePriority.HIGH.wire());
        assertEquals(IssuePriority.HIGH, IssuePriority.fromWire("!"));
        assertEquals("!!", IssuePriority.URGENT.wire());
        assertEquals(IssuePriority.URGENT, IssuePriority.fromWire("!!"));
    }

    @Test
    void rejectsAnUnknownWireValue() {
        assertThrows(IllegalArgumentException.class, () -> IssuePriority.fromWire("nope"));
    }
}
