// Generated by jails from art_ent_ticket_dto_response. Clean hand edits survive regeneration.
package com.example.demo.web;

import com.example.demo.domain.Ticket;

public record TicketResponse(
    long id,
    String subject
) {

    public static TicketResponse fromDomain(Ticket ticket) {
        return new TicketResponse(
                ticket.id(),
                ticket.subject());
    }
}
