// Generated by jails from art_cmp_cases_behaviour_cases. Clean hand edits survive regeneration.
package com.example.demo.cases;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

public class BehaviourCases {

    @Test
    @Disabled("pending implementation")
    @DisplayName("given a payout that is pending")
    void givenAPayoutThatIsPending() {
    }

    @Test
    @Disabled("pending implementation")
    @DisplayName("when the provider confirms it")
    void whenTheProviderConfirmsIt() {
    }

    @Test
    @Disabled("pending implementation")
    @DisplayName("then it is settled")
    void thenItIsSettled() {
    }

    @Test
    @Disabled("pending implementation")
    @DisplayName("given a payout that is pending")
    void givenAPayoutThatIsPending() {
    }

    @Test
    @Disabled("pending implementation")
    @DisplayName("when the provider declines it")
    void whenTheProviderDeclinesIt() {
    }

    @Test
    @Disabled("pending implementation")
    @DisplayName("then it is failed")
    void thenItIsFailed() {
    }

}
