-- Generated by jails from the accepted model.
create table topics (
    id bigint generated always as identity not null primary key,
    user_id bigint not null,
    subject text not null check (length(btrim(subject)) > 0),
    version bigint default 0 not null
);
