// Generated by jails from art_op_open_ticket_http_test. Clean hand edits survive regeneration.
package com.example.demo.adapters.http;

import static org.assertj.core.api.Assertions.assertThat;

import com.example.demo.domain.Ticket;
import org.junit.jupiter.api.Test;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.assertj.MockMvcTester;

class OpenTicketControllerTest {

    private final MockMvcTester mvc = MockMvcTester.of(new OpenTicketController((input) -> new Ticket(1L, "sample")));

    @Test
    void answersOnItsDeclaredRoute() {
        assertThat(mvc.post().uri("/actions/open-ticket")
                .contentType(MediaType.APPLICATION_JSON)
                .content("""
{
  "subject": "sample"
}
"""))
                .hasStatusOk();
    }

    // Reader-owned tests belong below this stable boundary.
}
