// Generated by jails from art_ent_operator_service. Clean hand edits survive regeneration.
package com.example.demo.service;

import com.example.demo.domain.Operator;
import com.example.demo.repository.OperatorRepository;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import org.springframework.stereotype.Component;

/**
 * What the application can do with {@link Operator}.
 *
 * <p>Depends on the port, not on an adapter, so a test can hand it an
 * in-memory implementation and never start a database.
 */
@Component
public class OperatorService {

    private final OperatorRepository repository;

    public OperatorService(OperatorRepository repository) {
        this.repository = Objects.requireNonNull(repository, "repository is required");
    }

    public Optional<Operator> byId(long id) {
        return repository.findById(id);
    }

    public List<Operator> all() {
        return repository.findAll();
    }

    public Operator save(Operator operator) {
        return repository.save(operator);
    }

    public boolean delete(long id) {
        return repository.deleteById(id);
    }

    // Reader-owned application methods belong below this stable boundary.
}
