// Generated by jails from art_ent_reward_record. Clean hand edits survive regeneration.
package com.example.demo.domain;

import java.util.Objects;
import java.util.UUID;

public record Reward(
    UUID id,
    long amount
) {

    public Reward {
        Objects.requireNonNull(id, "id");
    }
}
