// Generated by jails from art_ent_note_record. Clean hand edits survive regeneration.
package com.example.demo.domain;

import java.util.Objects;

public record Note(
    long id,
    String body,
    boolean seen,
    long version
) {

    public Note {
        Objects.requireNonNull(body, "body");
        body = body.trim();
        if (body.isEmpty()) {
            throw new IllegalArgumentException("body must not be blank");
        }
    }
}
