// Generated by jails from art_ent_item_repository. Clean hand edits survive regeneration.
package com.example.demo.repository;

import com.example.demo.domain.Item;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

public interface ItemRepository {

    Optional<Item> findById(UUID id);

    List<Item> findAll();

    Item save(Item item);

    boolean deleteById(UUID id);

    // Reader extensions belong below this stable boundary.
}
