// Generated by jails from art_ent_article_dto_request. Clean hand edits survive regeneration.
package com.example.demo.web;

import com.example.demo.domain.Article;
import com.example.demo.domain.TimeOrderedUuid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

public record ArticleRequest(
    @NotBlank String title,
    @NotNull String body
) {

    /**
     * The domain row this request describes, with every server-assigned
     * value supplied here rather than taken from the caller.
     */
    public Article toDomain() {
        return new Article(
                TimeOrderedUuid.next(),
                title,
                body);
    }
}
