// Generated by jails from art_cmp_client_open_ai_chat_interface. Clean hand edits survive regeneration.
package com.example.demo.clients;

import java.util.List;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.service.annotation.GetExchange;

/**
 * The OpenAiChat service, as this application uses it.
 *
 * <p>An interface and nothing else: Spring builds the implementation, and the
 * base URL is configuration (see {@link OpenAiChatClientConfig}), so pointing it
 * at a stub, staging or production is not a code change. It returns domain
 * types rather than {@code ResponseEntity} because a non-2xx response is
 * already an exception.
 */
public interface OpenAiChatClient {

    /** @return every item the upstream service knows about. */
    @GetExchange("/v1/chat/completions")
    List<OpenAiChatPayload> findAll();

    /** @return one item by id. A 404 upstream surfaces as an exception. */
    @GetExchange("/v1/chat/completions/{id}")
    OpenAiChatPayload findById(@PathVariable String id);

    /** Theirs, not yours: an external rename must not become a refactor here. */
    record OpenAiChatPayload(String id, String name) {}
}
