// Generated by jails from art_cmp_client_open_ai_chat_config. Clean hand edits survive regeneration.
package com.example.demo.clients;

import org.springframework.context.annotation.Configuration;
import org.springframework.web.service.registry.ImportHttpServices;

/**
 * Registers {@link OpenAiChatClient} as a bean, in its own group.
 *
 * <p>One class per client, listed by type: {@code @ImportHttpServices}
 * carries one group name, so a shared registration scanned by package loses
 * every earlier client's configuration when a second one is generated.
 *
 * <p>{@code spring.http.serviceclient.open-ai-chat.base-url} is where it points;
 * the same prefix carries timeouts, headers and SSL bundles.
 */
@Configuration(proxyBeanMethods = false)
@ImportHttpServices(group = "open-ai-chat", types = OpenAiChatClient.class)
public class OpenAiChatClientConfig {}
