// Generated by jails from art_ent_note_service. Clean hand edits survive regeneration.
package com.example.demo.service;

import com.example.demo.domain.Note;
import com.example.demo.repository.NoteRepository;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import org.springframework.stereotype.Component;

/**
 * What the application can do with {@link Note}.
 *
 * <p>Depends on the port, not on an adapter, so a test can hand it an
 * in-memory implementation and never start a database.
 */
@Component
public class NoteService {

    private final NoteRepository repository;

    public NoteService(NoteRepository repository) {
        this.repository = Objects.requireNonNull(repository, "repository is required");
    }

    public Optional<Note> byId(long id) {
        return repository.findById(id);
    }

    public List<Note> all() {
        return repository.findAll();
    }

    public Note save(Note note) {
        return repository.save(note);
    }

    public boolean delete(long id) {
        return repository.deleteById(id);
    }

    // Reader-owned application methods belong below this stable boundary.
}
