// Generated by jails from art_cap_db_ent_topic_repository. Clean hand edits survive regeneration.
package com.example.demo.adapters.jdbc;

import com.example.demo.domain.Topic;
import com.example.demo.repository.TopicRepository;
import java.util.List;
import java.util.Optional;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Repository;

@Repository
public final class JdbcTopicRepository implements TopicRepository {

    private final JdbcClient jdbc;

    public JdbcTopicRepository(JdbcClient jdbc) {
        this.jdbc = jdbc;
    }

    @Override
    public Optional<Topic> findById(long id) {
        return jdbc.sql("select id, user_id, subject, version from topics where id = :id")
                .param("id", id)
                .query(Topic.class)
                .optional();
    }

    @Override
    public List<Topic> findAll() {
        return jdbc.sql("select id, user_id, subject, version from topics order by id")
                .query(Topic.class)
                .list();
    }

    @Override
    public Topic save(Topic value) {
        return jdbc.sql("insert into topics (user_id, subject, version) values (:user_id, :subject, :version) returning id, user_id, subject, version")
                .param("user_id", value.userId())
                .param("subject", value.subject())
                .param("version", value.version())
                .query(Topic.class)
                .single();
    }

    @Override
    public boolean deleteById(long id) {
        return jdbc.sql("delete from topics where id = :id")
                .param("id", id)
                .update() > 0;
    }
}
