// Generated by jails from art_ent_operator_dto_test. Clean hand edits survive regeneration.
package com.example.demo.web;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Test;

final class OperatorDtoTest {

    @Test
    void theResponseProjectsEveryComponent() {
        assertEquals(List.of("id", "email"), componentNames(OperatorResponse.class));
    }

    /**
     * The request declares what a caller supplies and nothing else: an
     * audit column or an optimistic-lock version accepted from the body is
     * a value the server is supposed to be the authority on.
     */
    @Test
    void theRequestAsksOnlyForCallerSuppliedComponents() {
        assertEquals(List.of("email"), componentNames(OperatorRequest.class));
    }

    private static List<String> componentNames(Class<?> type) {
        return Arrays.stream(type.getRecordComponents())
                .map(component -> component.getName())
                .toList();
    }
}
