// Generated by jails from art_cmp_integration_test_checkout_test. Clean hand edits survive regeneration.
package com.example.demo;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

@Disabled("todo: wire the real integration boundary")
class CheckoutIT {

    @Test
    void worksEndToEnd() {
        throw new UnsupportedOperationException("todo");
    }
}
