// Generated by jails from art_cmp_test_parser_test. Clean hand edits survive regeneration.
package com.example.demo;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;

class ParserTest {

    @Test
    void shouldDoSomething() {
        assertTrue(true);
    }

}
