@baseUrl = http://localhost:8080

### Create Article
POST {{baseUrl}}/articles
Content-Type: application/json

{
  "id": "00000000-0000-0000-0000-000000000001",
  "title": "sample-title",
  "body": "sample-body"
}

### List Article
GET {{baseUrl}}/articles
Accept: application/json

@id = 00000000-0000-0000-0000-000000000001

### Get Article
GET {{baseUrl}}/articles/{{id}}
Accept: application/json

### Delete Article
DELETE {{baseUrl}}/articles/{{id}}
