// Generated by jails from art_cap_db_ent_note_repository. Clean hand edits survive regeneration.
package com.example.demo.adapters.jdbc;

import com.example.demo.domain.Note;
import com.example.demo.repository.NoteRepository;
import java.util.List;
import java.util.Optional;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Repository;

@Repository
public final class JdbcNoteRepository implements NoteRepository {

    private final JdbcClient jdbc;

    public JdbcNoteRepository(JdbcClient jdbc) {
        this.jdbc = jdbc;
    }

    @Override
    public Optional<Note> findById(long id) {
        return jdbc.sql("select id, author_id, body, sender_type from notes where id = :id")
                .param("id", id)
                .query(Note.class)
                .optional();
    }

    @Override
    public List<Note> findAll() {
        return jdbc.sql("select id, author_id, body, sender_type from notes order by id")
                .query(Note.class)
                .list();
    }

    @Override
    public Note save(Note value) {
        return jdbc.sql("insert into notes (author_id, body, sender_type) values (:author_id, :body, :sender_type) returning id, author_id, body, sender_type")
                .param("author_id", value.authorId())
                .param("body", value.body())
                .param("sender_type", value.senderType().name())
                .query(Note.class)
                .single();
    }

    @Override
    public boolean deleteById(long id) {
        return jdbc.sql("delete from notes where id = :id")
                .param("id", id)
                .update() > 0;
    }
}
