// Generated by jails from art_cap_db_op_post_admin_note_command. Clean hand edits survive regeneration.
package com.example.demo.adapters.jdbc;

import com.example.demo.application.commands.PostAdminNoteCommand;
import com.example.demo.domain.Note;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Repository;

@Repository
public class JdbcPostAdminNoteCommand implements PostAdminNoteCommand {

    private final JdbcClient jdbc;

    public JdbcPostAdminNoteCommand(JdbcClient jdbc) {
        this.jdbc = jdbc;
    }

    @Override
    public Note execute(PostAdminNoteCommand.Input input) {
        JdbcClient.StatementSpec statement = jdbc.sql("insert into notes (author_id, body, sender_type) values (:author_id, :body, 'ADMIN') returning id, author_id, body, sender_type");
        statement = statement.param("author_id", input.authorId());
        statement = statement.param("body", input.body());
        return statement.query(Note.class).single();
    }
}
