// Generated by jails from art_ent_note_factory. Clean hand edits survive regeneration.
package com.example.demo.testkit;

import com.example.demo.domain.Note;
import java.util.UUID;

/** Mutable test-data builder for {@link Note}. */
public final class NoteFactory {

    // State derived from canonical entity components.
    private UUID id = UUID.fromString("00000000-0000-0000-0000-000000000001");
    private String title = "sample";
    private String status = "sample";

    public static NoteFactory aNote() {
        return new NoteFactory();
    }

    // Fluent overrides derived from canonical entity components.
    public NoteFactory withId(UUID value) {
        this.id = value;
        return this;
    }

    public NoteFactory withTitle(String value) {
        this.title = value;
        return this;
    }

    public NoteFactory withStatus(String value) {
        this.status = value;
        return this;
    }

    public Note build() {
        return new Note(
                id,
                title,
                status);
    }
}
