// Generated by jails from art_ent_message_test. Clean hand edits survive regeneration.
package com.example.demo.domain;

import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.time.Instant;
import org.junit.jupiter.api.Test;

class MessageTest {

    @Test
    void rejectsANullComponent() {
        NullPointerException thrown =
                assertThrows(NullPointerException.class, () -> new Message(null, "sample", Instant.parse("2026-01-01T00:00:00Z")));
        assertTrue(thrown.getMessage().contains("id"));
    }
}
