// Generated by jails from art_op_change_payout_status_transition. Clean hand edits survive regeneration.
package com.example.demo.application.transitions;

import com.example.demo.domain.Payout;
import com.example.demo.domain.PayoutStatus;
import java.util.Objects;
import java.util.UUID;

public interface ChangePayoutStatusTransition {

    Payout execute(UUID id, Input input, long expectedVersion);

    public record Input(
        PayoutStatus status
    ) {

        public Input {
            Objects.requireNonNull(status, "status");
        }
    }
}
