// Generated by jails from art_ent_article_http. Clean hand edits survive regeneration.
package com.example.demo.ports.http;

import com.example.demo.domain.Article;

public interface ArticleHttpPort {

    Article create(Article request);
}
