-- Generated by jails from the accepted model.
create table messages (
    id uuid not null primary key,
    body text not null check (length(btrim(body)) > 0),
    created_at timestamptz default current_timestamp not null
);
