// Generated by jails from art_ent_ticket_http. Clean hand edits survive regeneration.
package com.example.demo.ports.http;

import com.example.demo.domain.Ticket;

public interface TicketHttpPort {

    Ticket create(Ticket request);
}
