// Generated by jails from art_ent_message_dto_response. Clean hand edits survive regeneration.
package com.example.demo.web;

import com.example.demo.domain.Message;
import java.time.Instant;
import java.util.UUID;

public record MessageResponse(
    UUID id,
    String body,
    Instant createdAt
) {

    public static MessageResponse fromDomain(Message message) {
        return new MessageResponse(
                message.id(),
                message.body(),
                message.createdAt());
    }
}
