[package]
name = "jails-drive"
version.workspace = true
edition.workspace = true

[dependencies]
clap.workspace = true
jails-generate.workspace = true
jails-commit.workspace = true
jails-java.workspace = true
jails-project.workspace = true
jails-protocol.workspace = true
jails-report.workspace = true
jails-spec.workspace = true
jails-support.workspace = true
tempfile.workspace = true

[lints]
workspace = true
