[package]
name = "jails-drive"
version.workspace = true
edition.workspace = true

[dependencies]
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
jails-codemod.workspace = true
jails-java.workspace = true
jails-project.workspace = true
jails-report.workspace = true
jails-spec.workspace = true
jails-support.workspace = true
tempfile.workspace = true

[lints]
workspace = true
