[package]
name = "jails-engine"
version.workspace = true
edition.workspace = true

[dependencies]
clap.workspace = true
jails-commit.workspace = true
jails-drive.workspace = true
jails-generate.workspace = true
jails-java.workspace = true
jails-prepare.workspace = true
jails-project.workspace = true
jails-protocol.workspace = true
jails-spec.workspace = true
jails-support.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
