//! **A primary key that sorts in the order rows were created.**
//!
//! `UUID.randomUUID()` is version 4: 122 random bits and no order.
//! `backend.md` §5 names it directly -- *"Do not use `uuidv4` /
//! `gen_random_uuid()` for a primary key on a large table -- random UUIDs
//! destroy b-tree locality."* -- and jails emitted one everywhere it minted a
//! key.
//!
//! The JDK has no version 7 factory, so this is a generated class rather than
//! a call. It is the same shape as `g auth`'s expiry validator and `add sse`'s
//! pool size: **the default is wrong in a way nothing reports**, and the
//! generated test is what keeps the fix in place, because a generator that
//! quietly went back to version 4 would look identical at every call site.
//!
//! Shared across every scaffold in the project, like `SchedulingConfig` and
//! the architecture suite, so `destroy` keeps it -- `tests/agreement.rs` says
//! why.

use super::*;

/// The class every server-assigned key is minted through.
pub(crate) const TIME_ORDERED_UUID: &str = "TimeOrderedUuid";

/// Where this project puts it: beside the domain types it names, which is the
/// one layer every other layer may already depend on.
pub(crate) fn package(slice: &Slice) -> String {
    slice.owned(Layer::Domain)
}

/// The expression that mints a key of this Java type, or `None` when the
/// application does not mint one.
pub(crate) fn mint(java_type: &str) -> Option<&'static str> {
    match java_type {
        "UUID" => Some("TimeOrderedUuid.next()"),
        "String" => Some("TimeOrderedUuid.next().toString()"),
        _ => None,
    }
}

/// The class and its test, written once per project.
///
/// Returns nothing when the file is already there: this is generated by
/// whichever scaffold ran first, and a second one must not rewrite it.
pub(crate) fn artifacts(slice: &Slice) -> Vec<Artifact> {
    let pkg = package(slice);
    let root: &Path = slice.project().root();
    let main = crate::generate::main_dir(root, &pkg).join(format!("{TIME_ORDERED_UUID}.java"));
    if main.is_file() {
        return Vec::new();
    }
    vec![
        Artifact {
            kind: "time-ordered identifier",
            path: main,
            contents: crate::template::render(
                crate::template_here!("spring/time_ordered_uuid_java.java"),
                &[("pkg", &*pkg)],
            ),
        },
        Artifact {
            kind: "time-ordered identifier test",
            path: crate::generate::test_dir(root, &pkg)
                .join(format!("{TIME_ORDERED_UUID}Test.java")),
            contents: crate::template::render(
                crate::template_here!("spring/time_ordered_uuid_test_java.java"),
                &[("pkg", &*pkg)],
            ),
        },
    ]
}
