// Generated by jails from art_ent_topic_http. Clean hand edits survive regeneration.
package com.example.demo.ports.http;

import com.example.demo.domain.Topic;

public interface TopicHttpPort {

    Topic create(Topic request);
}
