-- Generated by jails from the accepted model.
create table notes (
    id uuid not null primary key,
    title text not null check (length(btrim(title)) > 0),
    created_at timestamptz default current_timestamp not null
);
