// Generated by jails from art_ent_ticket_record. Clean hand edits survive regeneration.
package com.example.demo.domain;

import java.util.Objects;
import java.util.Optional;

public record Ticket(
    long id,
    String status,
    Optional<String> category
) {

    public Ticket {
        Objects.requireNonNull(status, "status");
        status = status.trim();
        if (status.isEmpty()) {
            throw new IllegalArgumentException("status must not be blank");
        }
        category = Objects.requireNonNullElse(category, Optional.empty());
    }
}
