// Generated by jails from art_cap_db_ent_note_repository. Clean hand edits survive regeneration.
package com.example.demo.adapters.jdbc;

import com.example.demo.domain.Note;
import com.example.demo.repository.NoteRepository;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Repository;

@Repository
public final class JdbcNoteRepository implements NoteRepository {

    private final JdbcClient jdbc;

    public JdbcNoteRepository(JdbcClient jdbc) {
        this.jdbc = jdbc;
    }

    @Override
    public Optional<Note> findById(UUID id) {
        return jdbc.sql("select id, title, status from notes where id = :id")
                .param("id", id)
                .query(Note.class)
                .optional();
    }

    @Override
    public List<Note> findAll() {
        return jdbc.sql("select id, title, status from notes order by id")
                .query(Note.class)
                .list();
    }

    @Override
    public Note save(Note value) {
        return jdbc.sql("insert into notes (id, title, status) values (:id, :title, :status) on conflict (id) do update set title = excluded.title, status = excluded.status returning id, title, status")
                .param("id", value.id())
                .param("title", value.title())
                .param("status", value.status())
                .query(Note.class)
                .single();
    }

    @Override
    public boolean deleteById(UUID id) {
        return jdbc.sql("delete from notes where id = :id")
                .param("id", id)
                .update() > 0;
    }
}
