// Generated by jails from art_cmp_notifier_main. Clean hand edits survive regeneration.
package com.example.demo.service;

import org.springframework.stereotype.Component;

@Component
class NotifierService {
}
