[package]
name = "jails-prepare"
version.workspace = true
edition.workspace = true

[dependencies]
jails-codec-derive.workspace = true
jails-java.workspace = true
jails-project.workspace = true
jails-protocol.workspace = true
jails-spec.workspace = true
jails-support.workspace = true

[lints]
workspace = true
