// Generated by jails from art_ent_money_test. Clean hand edits survive regeneration.
package com.example.demo.domain;

import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

class MoneyTest {

    @Test
    void rejectsANullComponent() {
        NullPointerException thrown =
                assertThrows(NullPointerException.class, () -> new Money(1L, null));
        assertTrue(thrown.getMessage().contains("currency"));
    }
}
