// Generated by jails from art_ent_owner_record. Clean hand edits survive regeneration.
package com.example.demo.domain;

import java.time.Instant;
import java.util.Objects;
import java.util.UUID;

public record Owner(
    UUID id,
    String name,
    Instant createdAt
) {

    public Owner {
        Objects.requireNonNull(id, "id");
        Objects.requireNonNull(name, "name");
        name = name.trim();
        if (name.isEmpty()) {
            throw new IllegalArgumentException("name must not be blank");
        }
        Objects.requireNonNull(createdAt, "createdAt");
    }
}
