// Generated by jails from art_ent_message_http_controller_test. Clean hand edits survive regeneration.
package com.example.demo.web;

import static org.assertj.core.api.Assertions.assertThat;

import com.example.demo.domain.Message;
import com.example.demo.repository.MessageRepository;
import com.example.demo.service.MessageService;
import java.time.Instant;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import org.junit.jupiter.api.Test;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.assertj.MockMvcTester;

class MessageControllerTest {

    private static final Message ROW = new Message(UUID.fromString("00000000-0000-0000-0000-000000000001"), "sample", Instant.parse("2026-01-01T00:00:00Z"));

    private static final MessageRepository REPOSITORY = new MessageRepository() {
        @Override
        public Optional<Message> findById(UUID id) {
            return Optional.of(ROW);
        }

        @Override
        public List<Message> findAll() {
            return List.of(ROW);
        }

        @Override
        public Message save(Message value) {
            return value;
        }

        @Override
        public boolean deleteById(UUID id) {
            return true;
        }
    };

    private static final String CREATE_REQUEST =
            """
            {
              "body": "sample-bodie"
            }""";

    private final MockMvcTester mvc = MockMvcTester.of(new MessageController(new MessageService(REPOSITORY)));

    @Test
    void theDocumentedCreateRequestIsAccepted() {
        assertThat(mvc.post().uri("/messages")
                .contentType(MediaType.APPLICATION_JSON)
                .content(CREATE_REQUEST))
                .hasStatus(201);
        assertThat(mvc.get().uri("/messages"))
                .hasStatusOk();
    }

    // Reader-owned tests belong below this stable boundary.
}
