-- Generated by jails from the accepted semantic schema.
create table tickets (
    id bigint generated always as identity not null primary key,
    status text not null check (length(btrim(status)) > 0),
    category text
);
