//! What to do when the generator, the base and the file on disk disagree.
//!
//! ## Why there is a table at all
//!
//! Three images — the base `B` jails last wrote, the live bytes `L`, and the
//! newly desired `N` — give a fixed set of situations, and each one has
//! exactly one defensible answer. Deciding them ad hoc at each call site is
//! how "the generator overwrote my edit" and "jails claimed a file I wrote"
//! both happen. plan.md §R5.3 enumerates them; this is that enumeration as a
//! function.
//!
//! ## The two rules worth stating on their own
//!
//! **Ownership requires adoption.** A file jails has never written is not
//! jails' to replace, *even when its bytes happen to match* what jails would
//! write. Silently claiming it would mean a later `destroy` deletes something
//! the user wrote. So the no-prior-output-with-a-live-file case is a refusal
//! that names the adoption path.
//!
//! **The base advances to `N`, never to merged bytes.** After a clean merge
//! the file contains the user's edit *and* the new generated content; if the
//! base became that, the user's edit would be folded into the baseline and
//! the next update would treat it as generator output. Keeping the base at
//! exact `N` keeps their edit a delta from the newest generated file, which
//! is the property that makes repeated updates survivable.
//!
//! ## Mode is reconciled separately, and refuses rather than guessing
//!
//! There is no marker syntax for a permission conflict and no later
//! finalisation step that could resolve one. So mode follows a closed
//! three-way rule of its own, and the one case where both sides changed it
//! differently is a refusal — a content conflict may commit marker bytes only
//! when the mode has one unambiguous answer.

use crate::Result;
use jails_protocol::conflict::{FileImage, FileMode};
use jails_protocol::identity::{ObjectRef, ProjectPath};
use jails_support::codec::{self, Encoder};

/// What jails last wrote to a path, if anything.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct PriorOutput {
    /// The exact generated bytes, not a reconstruction.
    pub base: ObjectRef,
    pub base_mode: FileMode,
}

/// What preparation should do with one path.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum Decision {
    /// Nothing to do, and no bookkeeping churn either.
    Nothing,
    Create {
        after: ObjectRef,
        mode: FileMode,
    },
    Replace {
        before: FileImage,
        after: ObjectRef,
        mode: FileMode,
    },
    Delete {
        before: FileImage,
    },
    /// The file already holds the desired bytes. No file operation, but the
    /// recorded base advances so the next update measures from the right
    /// place.
    AdvanceBase {
        after: ObjectRef,
        mode: FileMode,
    },
    /// The user changed it and the generator did not. Their bytes stay; the
    /// recorded *current* image follows them, and the base does not move.
    KeepUserBytes,
    /// All three differ and the text must be merged.
    Merge {
        base: ObjectRef,
        live: ObjectRef,
        desired: ObjectRef,
        /// Already reconciled: a merge only reaches here with one answer.
        mode: FileMode,
    },
    /// Nothing may be done without a person deciding.
    Refuse(String),
}

/// Decide one path.
pub fn reconcile(
    path: &ProjectPath,
    prior: Option<PriorOutput>,
    live: FileImage,
    desired: FileImage,
) -> Result<Decision> {
    match prior {
        None => Ok(unowned(path, live, desired)),
        Some(prior) => owned(path, prior, live, desired),
    }
}

/// A path jails has never written.
fn unowned(path: &ProjectPath, live: FileImage, desired: FileImage) -> Decision {
    match (live, desired) {
        (FileImage::Absent, FileImage::Absent) => Decision::Nothing,
        (FileImage::Absent, FileImage::Present { object, mode }) => Decision::Create {
            after: object,
            mode,
        },
        // A file jails did not write is preserved, and no row is created for
        // it: recording an output nothing generated would make `destroy`
        // delete it later.
        (FileImage::Present { .. }, FileImage::Absent) => Decision::Nothing,
        // Even when the bytes match. Ownership is a decision, not a
        // coincidence — see this module's header.
        (FileImage::Present { .. }, FileImage::Present { .. }) => Decision::Refuse(format!(
            "`{path}` already exists and jails did not write it.\n       fix: move it aside and \
             run this again, or generate into a different package. Claiming it because the \
             bytes happen to match would mean a later `destroy` deletes something you wrote."
        )),
    }
}

/// A path jails wrote before.
fn owned(
    path: &ProjectPath,
    prior: PriorOutput,
    live: FileImage,
    desired: FileImage,
) -> Result<Decision> {
    let base = FileImage::Present {
        object: prior.base,
        mode: prior.base_mode,
    };
    match (live, desired) {
        // The generator no longer wants it.
        (FileImage::Absent, FileImage::Absent) => Ok(Decision::Nothing),
        (live, FileImage::Absent) if live == base => Ok(Decision::Delete { before: live }),
        (FileImage::Present { .. }, FileImage::Absent) => Ok(Decision::Refuse(format!(
            "`{path}` was edited after jails wrote it, and the generator no longer produces \
             it.\n       fix: `--force` removes it and records what was discarded."
        ))),
        // A file jails owns that somebody deleted. Recreating it silently
        // would undo a deliberate removal.
        (FileImage::Absent, FileImage::Present { .. }) => Ok(Decision::Refuse(format!(
            "`{path}` is a generated file that has been deleted.\n       fix: `--replace` \
             recreates it deliberately."
        ))),
        (
            FileImage::Present {
                object: live_object,
                mode: live_mode,
            },
            FileImage::Present {
                object: desired_object,
                mode: desired_mode,
            },
        ) => {
            let unchanged_live = live == base;
            let unchanged_desired = desired == base;
            match (unchanged_live, unchanged_desired) {
                // Nobody moved.
                (true, true) => Ok(Decision::Nothing),
                // Only the generator moved.
                (true, false) => Ok(Decision::Replace {
                    before: base,
                    after: desired_object,
                    mode: desired_mode,
                }),
                // Only the user moved.
                (false, true) => Ok(Decision::KeepUserBytes),
                (false, false) if live == desired => Ok(Decision::AdvanceBase {
                    after: desired_object,
                    mode: desired_mode,
                }),
                (false, false) => Ok(Decision::Merge {
                    base: prior.base,
                    live: live_object,
                    desired: desired_object,
                    mode: merge_mode(path, prior.base_mode, live_mode, desired_mode)?,
                }),
            }
        }
    }
}

/// The closed three-way rule for permission bits.
///
/// There is no marker syntax for a mode conflict and no finalisation step
/// that could resolve one, so the case where both sides changed it
/// differently refuses rather than picking.
pub fn merge_mode(
    path: &ProjectPath,
    base: FileMode,
    live: FileMode,
    desired: FileMode,
) -> Result<FileMode> {
    if live == base {
        return Ok(desired);
    }
    if desired == base {
        return Ok(live);
    }
    if live == desired {
        return Ok(live);
    }
    Err(format!(
        "`{path}` has permission {:o} and jails wants {:o}, from {:o}.\n       fix: both were \
         changed, and there is no marker syntax for a permission conflict. Set it to one of the \
         two and run again.",
        live.bits(),
        desired.bits(),
        base.bits()
    ))
}

/// `SHA256("JAILS-MERGE-PATH-1" || encode(path))`, lowercase hex.
///
/// The merge inputs are laid out under this rather than under the project
/// path, so no absolute or user-chosen path enters the merge tool's argv —
/// which is what keeps the tool fingerprint the same on two machines.
pub fn path_key(path: &ProjectPath) -> Result<String> {
    let mut encoder = Encoder::new();
    path.encode(&mut encoder)?;
    Ok(codec::hex(&codec::domain_hash(
        "JAILS-MERGE-PATH-1",
        &encoder.finish()?,
    )))
}

/// The exact marker lines a conflicted merge must contain.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MarkerTokens {
    pub start: String,
    pub separator: String,
    pub end: String,
}

impl MarkerTokens {
    /// Built from the operation id, so a conflict a person is looking at
    /// names the operation that produced it.
    pub fn for_operation(operation_hex: &str) -> Self {
        Self {
            start: "<<<<<<< current".to_string(),
            separator: "=======".to_string(),
            end: format!(">>>>>>> jails-desired-{}", &operation_hex[..12]),
        }
    }
}

/// Check that merge output is the shape it claims to be.
///
/// §R5.3 requires the exact token lines in order, at least one hunk, no
/// nesting, and an exit status equal to `min(hunk_count, 127)` — Git reports
/// the conflict count and truncates it there. Accepting output without this
/// would let a tool failure, or a file that merely contains something
/// marker-shaped, pass as a merge result.
pub fn validate_conflict(text: &str, tokens: &MarkerTokens, exit_status: i32) -> Result<usize> {
    #[derive(PartialEq)]
    enum Where {
        Outside,
        InCurrent,
        InDesired,
    }
    let mut state = Where::Outside;
    let mut hunks = 0usize;
    for line in text.lines() {
        if line == tokens.start {
            if state != Where::Outside {
                return Err("merge output nests conflict markers".to_string());
            }
            state = Where::InCurrent;
        } else if line == tokens.separator {
            if state != Where::InCurrent {
                return Err("merge output has a separator outside a conflict".to_string());
            }
            state = Where::InDesired;
        } else if line == tokens.end {
            if state != Where::InDesired {
                return Err("merge output closes a conflict that never opened".to_string());
            }
            state = Where::Outside;
            hunks += 1;
        }
    }
    if state != Where::Outside {
        return Err("merge output leaves a conflict unclosed".to_string());
    }
    if hunks == 0 {
        return Err(
            "the merge tool reported a conflict and produced no conflict markers".to_string(),
        );
    }
    let expected = hunks.min(127) as i32;
    if exit_status != expected {
        return Err(format!(
            "the merge tool exited {exit_status} and produced {hunks} conflict(s); it reports \
             the count, truncated at 127"
        ));
    }
    Ok(hunks)
}

/// Whether a resolved file still carries anything marker-shaped.
///
/// Finalisation refuses on any generic seven-character marker line, not only
/// on the exact tokens: a person who edited the markers by hand rather than
/// resolving the conflict has not resolved it.
pub fn still_conflicted(text: &str) -> bool {
    text.lines().any(|line| {
        let seven = |c: char| line.starts_with(&c.to_string().repeat(7));
        seven('<') || seven('=') || seven('>')
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use jails_protocol::identity::ObjectId;
    use jails_support::codec::sha256;

    fn path() -> ProjectPath {
        ProjectPath::parse("src/main/java/App.java").unwrap()
    }

    fn mode() -> FileMode {
        FileMode::new(0o644).unwrap()
    }

    fn object(seed: &str) -> ObjectRef {
        ObjectRef::new(
            ObjectId::from_bytes(sha256(seed.as_bytes())),
            seed.len() as u64,
        )
    }

    fn present(seed: &str) -> FileImage {
        FileImage::Present {
            object: object(seed),
            mode: mode(),
        }
    }

    fn prior(seed: &str) -> PriorOutput {
        PriorOutput {
            base: object(seed),
            base_mode: mode(),
        }
    }

    #[test]
    fn a_new_file_is_created() {
        assert_eq!(
            reconcile(&path(), None, FileImage::Absent, present("N")).unwrap(),
            Decision::Create {
                after: object("N"),
                mode: mode()
            }
        );
    }

    /// Ownership is a decision, not a coincidence: claiming a matching file
    /// would mean a later `destroy` deletes something the user wrote.
    #[test]
    fn an_existing_file_jails_did_not_write_is_refused_even_when_it_matches() {
        let decision = reconcile(&path(), None, present("N"), present("N")).unwrap();
        match decision {
            Decision::Refuse(why) => assert!(why.contains("jails did not write it"), "{why}"),
            other => panic!("expected a refusal, got {other:?}"),
        }
    }

    #[test]
    fn an_unmanaged_file_the_generator_does_not_want_is_left_alone() {
        assert_eq!(
            reconcile(&path(), None, present("theirs"), FileImage::Absent).unwrap(),
            Decision::Nothing
        );
    }

    #[test]
    fn an_unchanged_owned_file_the_generator_changed_is_replaced() {
        assert_eq!(
            reconcile(&path(), Some(prior("B")), present("B"), present("N")).unwrap(),
            Decision::Replace {
                before: present("B"),
                after: object("N"),
                mode: mode()
            }
        );
    }

    #[test]
    fn nobody_moving_produces_no_churn_at_all() {
        assert_eq!(
            reconcile(&path(), Some(prior("B")), present("B"), present("B")).unwrap(),
            Decision::Nothing
        );
    }

    /// The user's bytes stay and the base does not move, so the next
    /// generator change still measures from what jails last wrote.
    #[test]
    fn a_user_edit_the_generator_did_not_touch_is_kept() {
        assert_eq!(
            reconcile(&path(), Some(prior("B")), present("mine"), present("B")).unwrap(),
            Decision::KeepUserBytes
        );
    }

    /// The file already holds what the generator wants; there is nothing to
    /// write, but the base has to advance or the next update merges against
    /// a stale baseline.
    #[test]
    fn a_file_that_already_holds_the_desired_bytes_advances_the_base() {
        assert_eq!(
            reconcile(&path(), Some(prior("B")), present("N"), present("N")).unwrap(),
            Decision::AdvanceBase {
                after: object("N"),
                mode: mode()
            }
        );
    }

    #[test]
    fn all_three_differing_is_a_merge() {
        assert_eq!(
            reconcile(&path(), Some(prior("B")), present("mine"), present("N")).unwrap(),
            Decision::Merge {
                base: object("B"),
                live: object("mine"),
                desired: object("N"),
                mode: mode()
            }
        );
    }

    /// Recreating a file somebody deleted would undo a deliberate removal.
    #[test]
    fn a_deleted_owned_output_is_refused_rather_than_recreated() {
        match reconcile(&path(), Some(prior("B")), FileImage::Absent, present("N")).unwrap() {
            Decision::Refuse(why) => assert!(why.contains("--replace"), "{why}"),
            other => panic!("expected a refusal, got {other:?}"),
        }
    }

    #[test]
    fn an_unchanged_owned_file_the_generator_dropped_is_deleted() {
        assert_eq!(
            reconcile(&path(), Some(prior("B")), present("B"), FileImage::Absent).unwrap(),
            Decision::Delete {
                before: present("B")
            }
        );
    }

    #[test]
    fn an_edited_owned_file_the_generator_dropped_needs_force() {
        match reconcile(
            &path(),
            Some(prior("B")),
            present("mine"),
            FileImage::Absent,
        )
        .unwrap()
        {
            Decision::Refuse(why) => assert!(why.contains("--force"), "{why}"),
            other => panic!("expected a refusal, got {other:?}"),
        }
    }

    /// There is no marker syntax for a permission conflict and no
    /// finalisation step that could resolve one.
    #[test]
    fn mode_follows_its_own_three_way_rule_and_refuses_a_real_conflict() {
        let base = FileMode::new(0o644).unwrap();
        let executable = FileMode::new(0o755).unwrap();
        let other = FileMode::new(0o600).unwrap();

        assert_eq!(
            merge_mode(&path(), base, base, executable).unwrap(),
            executable
        );
        assert_eq!(
            merge_mode(&path(), base, executable, base).unwrap(),
            executable
        );
        assert_eq!(
            merge_mode(&path(), base, executable, executable).unwrap(),
            executable
        );
        let error = merge_mode(&path(), base, executable, other).unwrap_err();
        assert!(error.contains("no marker syntax"), "{error}");
    }

    /// No absolute or user-chosen path enters the merge tool's argv, which is
    /// what keeps its fingerprint the same on two machines.
    #[test]
    fn a_merge_input_is_keyed_by_a_hash_of_the_path() {
        let key = path_key(&path()).unwrap();
        assert_eq!(key.len(), 64);
        assert!(
            key.chars()
                .all(|c| c.is_ascii_hexdigit() && !c.is_uppercase())
        );
        assert_ne!(
            key,
            path_key(&ProjectPath::parse("pom.xml").unwrap()).unwrap()
        );
    }

    fn tokens() -> MarkerTokens {
        MarkerTokens::for_operation("0123456789abcdef0123")
    }

    #[test]
    fn a_well_formed_conflict_is_accepted_with_its_count() {
        let text = format!(
            "one\n{}\nmine\n{}\ntheirs\n{}\ntail\n",
            tokens().start,
            tokens().separator,
            tokens().end
        );
        assert_eq!(validate_conflict(&text, &tokens(), 1).unwrap(), 1);
    }

    /// Accepting output without this would let a tool failure, or a file that
    /// merely contains something marker-shaped, pass as a merge result.
    #[test]
    fn malformed_merge_output_is_refused() {
        let good = format!(
            "{}\nmine\n{}\ntheirs\n{}\n",
            tokens().start,
            tokens().separator,
            tokens().end
        );
        // Nested.
        let nested = format!("{}\n{good}{}\n", tokens().start, tokens().end);
        assert!(validate_conflict(&nested, &tokens(), 2).is_err());
        // No hunks at all, but a nonzero status.
        assert!(validate_conflict("clean\n", &tokens(), 1).is_err());
        // Unclosed.
        let unclosed = format!("{}\nmine\n", tokens().start);
        assert!(validate_conflict(&unclosed, &tokens(), 1).is_err());
        // The count and the status must agree.
        assert!(validate_conflict(&good, &tokens(), 3).is_err());
    }

    /// Somebody who edited the markers by hand rather than resolving the
    /// conflict has not resolved it.
    #[test]
    fn a_resolution_still_carrying_any_marker_line_is_not_resolved() {
        assert!(still_conflicted("<<<<<<< anything\n"));
        assert!(still_conflicted("=======\n"));
        assert!(still_conflicted(">>>>>>> whatever\n"));
        assert!(!still_conflicted("class App {}\n"));
        // Six is not seven: a divider comment is not a marker.
        assert!(!still_conflicted("// ======\n"));
    }
}
