// Generated by jails from art_ent_author_dto_request. Clean hand edits survive regeneration.
package com.example.demo.web;

import com.example.demo.domain.Author;
import jakarta.validation.constraints.NotBlank;

public record AuthorRequest(
    @NotBlank String email
) {

    /**
     * The domain row this request describes, with every server-assigned
     * value supplied here rather than taken from the caller.
     */
    public Author toDomain() {
        return new Author(
                0L,
                email);
    }
}
