# syntax=docker/dockerfile:1
{{BUILD_STAGE}}

FROM eclipse-temurin:{{RELEASE}}-jre-noble
WORKDIR /app
COPY --from=build --chown=10001:10001 /build/application.jar /app/application.jar
USER 10001:10001
EXPOSE 8080
ENTRYPOINT ["java", "-XX:MaxRAMPercentage=75.0", "-Djava.io.tmpdir=/tmp", "-jar", "/app/application.jar"]
