FROM maven:3.9.16-eclipse-temurin-{{RELEASE}} AS build
WORKDIR /build
COPY pom.xml ./
COPY src/ src/
RUN --mount=type=cache,id=jails-maven-repository,target=/root/.m2 \
    mvn -B -ntp -DskipTests package \
    && cp "$(find target -maxdepth 1 -type f -name '*.jar' ! -name '*.original' -print -quit)" /build/application.jar
