// Generated by jails from art_ent_topic_record. Clean hand edits survive regeneration.
package com.example.demo.domain;

import java.util.Objects;

public record Topic(
    long id,
    long userId,
    String subject,
    long version
) {

    public Topic {
        Objects.requireNonNull(subject, "subject");
        subject = subject.trim();
        if (subject.isEmpty()) {
            throw new IllegalArgumentException("subject must not be blank");
        }
    }
}
