// Generated by jails from art_cap_db_ent_ticket_repository. Clean hand edits survive regeneration.
package com.example.demo.adapters.jdbc;

import com.example.demo.domain.Ticket;
import com.example.demo.repository.TicketRepository;
import java.util.List;
import java.util.Optional;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Repository;

@Repository
public final class JdbcTicketRepository implements TicketRepository {

    private final JdbcClient jdbc;

    public JdbcTicketRepository(JdbcClient jdbc) {
        this.jdbc = jdbc;
    }

    @Override
    public Optional<Ticket> findById(long id) {
        return jdbc.sql("select id, status, category from tickets where id = :id")
                .param("id", id)
                .query(Ticket.class)
                .optional();
    }

    @Override
    public List<Ticket> findAll() {
        return jdbc.sql("select id, status, category from tickets order by id")
                .query(Ticket.class)
                .list();
    }

    @Override
    public Ticket save(Ticket value) {
        return jdbc.sql("insert into tickets (status, category) values (:status, :category) returning id, status, category")
                .param("status", value.status())
                .param("category", value.category().orElse(null))
                .query(Ticket.class)
                .single();
    }

    @Override
    public boolean deleteById(long id) {
        return jdbc.sql("delete from tickets where id = :id")
                .param("id", id)
                .update() > 0;
    }
}
