// Generated by jails from art_ent_person_repository. Clean hand edits survive regeneration.
package com.example.demo.repository;

import com.example.demo.domain.Person;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

public interface PersonRepository {

    Optional<Person> findById(UUID id);

    List<Person> findAll();

    Person save(Person person);

    boolean deleteById(UUID id);

    // Reader extensions belong below this stable boundary.
}
