// Generated by jails from art_ent_owner_http_controller_test. Clean hand edits survive regeneration.
package com.example.demo.web;

import static org.assertj.core.api.Assertions.assertThat;

import com.example.demo.domain.Owner;
import com.example.demo.repository.OwnerRepository;
import com.example.demo.service.OwnerService;
import java.time.Instant;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import org.junit.jupiter.api.Test;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.assertj.MockMvcTester;

class OwnerControllerTest {

    private static final Owner ROW = new Owner(UUID.fromString("00000000-0000-0000-0000-000000000001"), "sample", Instant.parse("2026-01-01T00:00:00Z"));

    private static final OwnerRepository REPOSITORY = new OwnerRepository() {
        @Override
        public Optional<Owner> findById(UUID id) {
            return Optional.of(ROW);
        }

        @Override
        public List<Owner> findAll() {
            return List.of(ROW);
        }

        @Override
        public Owner save(Owner value) {
            return value;
        }

        @Override
        public boolean deleteById(UUID id) {
            return true;
        }
    };

    private static final String CREATE_REQUEST =
            """
            {
              "name": "sample-name"
            }""";

    private final MockMvcTester mvc = MockMvcTester.of(new OwnerController(new OwnerService(REPOSITORY)));

    @Test
    void theDocumentedCreateRequestIsAccepted() {
        assertThat(mvc.post().uri("/owners")
                .contentType(MediaType.APPLICATION_JSON)
                .content(CREATE_REQUEST))
                .hasStatus(201);
        assertThat(mvc.get().uri("/owners"))
                .hasStatusOk();
    }

    // Reader-owned tests belong below this stable boundary.
}
