// Generated by jails from art_op_transaction_settled_messaging_it. Clean hand edits survive regeneration.
package com.example.demo.messaging;

import static org.assertj.core.api.Assertions.assertThat;

import com.example.demo.KafkaTestcontainersConfig;
import com.example.demo.domain.events.TransactionSettledEvent;
import java.util.UUID;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Import;
import org.springframework.kafka.annotation.KafkaListener;

/**
 * Publishes through a real broker and waits for it to come back.
 *
 * <p>An {@code IT}, so Failsafe runs it in {@code verify} rather than on
 * every {@code jails test}: starting a broker costs tens of seconds.
 *
 * <p>{@code @ServiceConnection} points the application at the container --
 * no bootstrap-servers property to override, and no chance of a test quietly
 * using the developer's own broker.
 *
 * <p>The wait is the part worth copying. Consumption is asynchronous, so an
 * assertion made straight after publishing races the consumer and fails about
 * one run in five. Waiting with a timeout either observes the message or
 * fails saying so -- and it waits for <em>this</em> event by id, not for the
 * next one on the topic.
 */
@SpringBootTest(properties = {
    "spring.kafka.consumer.properties.group.protocol=classic",
    "spring.kafka.listener.auto-startup=true"
})
@Import({ KafkaTestcontainersConfig.class, TransactionSettledMessagingIT.ProbeConfiguration.class })
class TransactionSettledMessagingIT {

    @Autowired
    private TransactionSettledPublisher publisher;

    @Autowired
    private Probe probe;

    @Test
    void aPublishedEventIsConsumed() throws InterruptedException {
        TransactionSettledEvent event = new TransactionSettledEvent(UUID.fromString("00000000-0000-0000-0000-000000000001"));

        publisher.publish(event);

        assertThat(probe.await(event.id(), 30))
                .as("the published event should have been consumed within 30s")
                .isTrue();
    }

    /**
     * The probe has to be a *bean*, not a method on the test class.
     *
     * <p>{@code @KafkaListener} is registered by a bean post-processor, and
     * a test instance is not a bean -- Spring creates it and injects into it,
     * but never processes its annotations. A listener declared on the test
     * class is therefore silently never subscribed, and the only symptom is a
     * wait that times out with nothing in the log to explain it.
     */
    static class Probe {

        private final BlockingQueue<TransactionSettledEvent> received = new LinkedBlockingQueue<>();

        /**
         * Its own consumer group, so it does not compete with the
         * application's listener: two consumers in one group split the
         * partitions and each message reaches only one of them.
         */
        @KafkaListener(topics = "${topics.transaction-settled:transaction-settled}", groupId = "transaction-settled-it-probe")
        void on(TransactionSettledEvent event) {
            received.add(event);
        }

        /**
         * Waits for the event with this id, not for the next event on the
         * topic.
         *
         * <p>The probe's consumer group is new, so {@code
         * auto-offset-reset=earliest} replays everything already published --
         * including whatever a neighbouring test or an outbox delivery put
         * there. Asserting on whichever record arrived first makes this test
         * pass or fail on what its neighbours did, and it passes by accident
         * whenever their ids happen to agree with this one's.
         */
        boolean await(Object id, long seconds) throws InterruptedException {
            long deadline = System.nanoTime() + TimeUnit.SECONDS.toNanos(seconds);
            for (long left = deadline - System.nanoTime(); left > 0; left = deadline - System.nanoTime()) {
                TransactionSettledEvent next = received.poll(left, TimeUnit.NANOSECONDS);
                if (next == null) {
                    return false;
                }
                if (id.equals(next.id())) {
                    return true;
                }
            }
            return false;
        }
    }

    @org.springframework.boot.test.context.TestConfiguration(proxyBeanMethods = false)
    static class ProbeConfiguration {

        @org.springframework.context.annotation.Bean
        Probe probe() {
            return new Probe();
        }
    }
}
