// Generated by jails from art_op_transaction_settled_listener_test. Clean hand edits survive regeneration.
package com.example.demo.messaging;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;

import com.example.demo.domain.events.TransactionSettledEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.junit.jupiter.api.Test;

/**
 * The listener routes to the port, and says so when nothing is listening.
 *
 * <p>No broker and no Spring context: the listener is an ordinary object with
 * a constructor, which is the point of putting the reaction behind
 * {@link TransactionSettledHandler}. The companion {@code MessagingIT} proves a record
 * makes the round trip through a real broker; this proves the class in the
 * middle does something with it.
 *
 * <p>The empty case is the one worth keeping. A listener that logs a record
 * and drops it passes every test that only checks delivery, so the assertion
 * is that consuming without a handler is survivable and visible rather than
 * silent.
 */
class TransactionSettledListenerTest {

    @Test
    void everyRegisteredHandlerSeesTheEvent() {
        List<TransactionSettledEvent> first = new ArrayList<>();
        List<TransactionSettledEvent> second = new ArrayList<>();
        TransactionSettledListener listener = new TransactionSettledListener(List.of(first::add, second::add));
        TransactionSettledEvent event = new TransactionSettledEvent(UUID.fromString("00000000-0000-0000-0000-000000000001"));

        listener.on(event);

        assertThat(first).containsExactly(event);
        assertThat(second).containsExactly(event);
    }

    @Test
    void aRecordWithNoHandlerIsSurvivable() {
        TransactionSettledListener listener = new TransactionSettledListener(List.of());

        assertThatCode(() -> listener.on(new TransactionSettledEvent(UUID.fromString("00000000-0000-0000-0000-000000000001"))))
                .doesNotThrowAnyException();
    }
}
