// Generated by jails from art_cap_db_ent_note_repository_it. Clean hand edits survive regeneration.
package com.example.demo.adapters.jdbc;

import com.example.demo.TestcontainersConfig;
import com.example.demo.domain.Note;
import com.example.demo.repository.NoteRepository;
import com.example.demo.repository.NoteRepositoryContract;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Import;
import org.springframework.transaction.annotation.Transactional;

@Import(TestcontainersConfig.class)
@SpringBootTest
@Transactional
class JdbcNoteRepositoryIT {

    @Autowired
    private NoteRepository repository;

    @Test
    void satisfiesTheNoteRepositoryContractAgainstTheRealDatabase() {
        NoteRepositoryContract.savesReadsAndDeletes(
                repository, new Note(1L, "sample", false, 1L));
    }

    // Reader-owned cases belong below this stable boundary.
}
