// Generated by jails from art_ent_author_repository. Clean hand edits survive regeneration.
package com.example.demo.repository;

import com.example.demo.domain.Author;
import java.util.List;
import java.util.Optional;

public interface AuthorRepository {

    Optional<Author> findById(long id);

    List<Author> findAll();

    Author save(Author author);

    boolean deleteById(long id);

    // Reader extensions belong below this stable boundary.
}
