-- Generated by jails from the accepted semantic schema.
create table notes (
    id bigint generated always as identity not null primary key,
    body text not null check (length(btrim(body)) > 0),
    seen boolean not null,
    version bigint default 0 not null
);
