// Generated by jails from art_ent_note_test. Clean hand edits survive regeneration.
package com.example.demo.domain;

import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.time.Instant;
import java.util.Optional;
import org.junit.jupiter.api.Test;

class NoteTest {

    @Test
    void rejectsANullComponent() {
        NullPointerException thrown =
                assertThrows(NullPointerException.class, () -> new Note(null, Optional.empty(), Instant.parse("2026-01-01T00:00:00Z")));
        assertTrue(thrown.getMessage().contains("title"));
    }
}
