// Generated by jails from art_cmp_strategy_reward_rule_test_coffee. Clean hand edits survive regeneration.
package com.example.demo.service;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;

class CoffeeRewardRuleTest {

    @Test
    void startsWithNoMatch() {
        assertTrue(new CoffeeRewardRule().evaluate(null).isEmpty());
    }

    // Reader-owned tests belong below this stable boundary.
}
