// Generated by jails from art_ent_article_test. Clean hand edits survive regeneration.
package com.example.demo.domain;

import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

class ArticleTest {

    @Test
    void rejectsANullComponent() {
        NullPointerException thrown =
                assertThrows(NullPointerException.class, () -> new Article(null, "sample", "sample"));
        assertTrue(thrown.getMessage().contains("id"));
    }
}
