// Generated by jails from art_op_message_received_listener. Clean hand edits survive regeneration.
package com.example.demo.messaging;

import com.example.demo.domain.events.MessageReceivedEvent;
import java.util.List;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.stereotype.Component;

/**
 * Consumes {@link MessageReceivedEvent} and hands it to every {@link MessageReceivedHandler}.
 *
 * <p>The listener is deliberately thin. Business logic inside a listener is
 * unreachable from any test that does not start a broker, and unreusable from
 * any other entry point -- so the reaction lives behind the handler port and
 * this class only routes to it.
 *
 * <p>Spring injects every {@code @Component} implementing the port. With none
 * registered the list is empty, and the first record says so at {@code WARN}
 * rather than being logged as received and then dropped: a consumer that
 * silently discards a topic is indistinguishable from one that is working.
 *
 * <p>Nothing here catches exceptions. That is the right default -- a thrown
 * exception means the offset is not committed, so the message is retried and
 * eventually goes to a dead-letter topic if one is configured. Swallowing it
 * would acknowledge a message that was never processed, which is data loss
 * that looks like success.
 */
@Component
public class MessageReceivedListener {

    private static final Logger log = LoggerFactory.getLogger(MessageReceivedListener.class);

    private final List<MessageReceivedHandler> handlers;

    public MessageReceivedListener(List<MessageReceivedHandler> handlers) {
        this.handlers = List.copyOf(handlers);
    }

    @KafkaListener(topics = "${topics.message-received:message-received}")
    public void on(MessageReceivedEvent event) {
        if (handlers.isEmpty()) {
            // The whole record, not its id: an event is not required to carry
            // one, and a listener that names a component the payload may not
            // have is a listener that does not compile.
            log.warn("no MessageReceivedHandler is registered: {} was consumed and discarded", event);
            return;
        }
        for (MessageReceivedHandler handler : handlers) {
            handler.handle(event);
        }
    }
}
