// Generated by jails from art_cap_db_ent_owner_repository. Clean hand edits survive regeneration.
package com.example.demo.adapters.jdbc;

import com.example.demo.domain.Owner;
import com.example.demo.repository.OwnerRepository;
import java.sql.Timestamp;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Repository;

@Repository
public final class JdbcOwnerRepository implements OwnerRepository {

    private final JdbcClient jdbc;

    public JdbcOwnerRepository(JdbcClient jdbc) {
        this.jdbc = jdbc;
    }

    @Override
    public Optional<Owner> findById(UUID id) {
        return jdbc.sql("select id, email, created_at from owners where id = :id")
                .param("id", id)
                .query(Owner.class)
                .optional();
    }

    @Override
    public List<Owner> findAll() {
        return jdbc.sql("select id, email, created_at from owners order by id")
                .query(Owner.class)
                .list();
    }

    @Override
    public Owner save(Owner value) {
        return jdbc.sql("insert into owners (id, email, created_at) values (:id, :email, :created_at) on conflict (id) do update set email = excluded.email, created_at = excluded.created_at returning id, email, created_at")
                .param("id", value.id())
                .param("email", value.email())
                .param("created_at", Timestamp.from(value.createdAt()))
                .query(Owner.class)
                .single();
    }

    @Override
    public boolean deleteById(UUID id) {
        return jdbc.sql("delete from owners where id = :id")
                .param("id", id)
                .update() > 0;
    }
}
