// Generated by jails from art_cap_db_ent_item_repository. Clean hand edits survive regeneration.
package com.example.demo.adapters.jdbc;

import com.example.demo.domain.Item;
import com.example.demo.repository.ItemRepository;
import java.sql.Timestamp;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Repository;

@Repository
public final class JdbcItemRepository implements ItemRepository {

    private final JdbcClient jdbc;

    public JdbcItemRepository(JdbcClient jdbc) {
        this.jdbc = jdbc;
    }

    @Override
    public Optional<Item> findById(UUID id) {
        return jdbc.sql("select id, owner_id, name, created_at from items where id = :id")
                .param("id", id)
                .query(Item.class)
                .optional();
    }

    @Override
    public List<Item> findAll() {
        return jdbc.sql("select id, owner_id, name, created_at from items order by id")
                .query(Item.class)
                .list();
    }

    @Override
    public Item save(Item value) {
        return jdbc.sql("insert into items (id, owner_id, name, created_at) values (:id, :owner_id, :name, :created_at) on conflict (id) do update set owner_id = excluded.owner_id, name = excluded.name, created_at = excluded.created_at returning id, owner_id, name, created_at")
                .param("id", value.id())
                .param("owner_id", value.ownerId())
                .param("name", value.name())
                .param("created_at", Timestamp.from(value.createdAt()))
                .query(Item.class)
                .single();
    }

    @Override
    public boolean deleteById(UUID id) {
        return jdbc.sql("delete from items where id = :id")
                .param("id", id)
                .update() > 0;
    }
}
