// Generated by jails from art_ent_note_repository_memory. Clean hand edits survive regeneration.
package com.example.demo.adapters.memory;

import com.example.demo.domain.Note;
import com.example.demo.repository.NoteRepository;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;

public final class InMemoryNoteRepository implements NoteRepository {

    private final Map<UUID, Note> rows = new LinkedHashMap<>();

    @Override
    public Optional<Note> findById(UUID id) {
        return Optional.ofNullable(rows.get(id));
    }

    @Override
    public List<Note> findAll() {
        return List.copyOf(rows.values());
    }

    @Override
    public Note save(Note value) {
        rows.put(value.id(), value);
        return value;
    }

    @Override
    public boolean deleteById(UUID id) {
        return rows.remove(id) != null;
    }
}
