// Generated by jails from art_ent_note_repository. Clean hand edits survive regeneration.
package com.example.demo.repository;

import com.example.demo.domain.Note;
import java.util.List;
import java.util.Optional;

public interface NoteRepository {

    Optional<Note> findById(long id);

    List<Note> findAll();

    Note save(Note note);

    boolean deleteById(long id);

    // Reader extensions belong below this stable boundary.
}
