// Generated by jails from art_ent_note_dto_response. Clean hand edits survive regeneration.
package com.example.demo.web;

import com.example.demo.domain.Note;
import java.time.Instant;
import java.util.UUID;

public record NoteResponse(
    UUID id,
    String title,
    Instant createdAt
) {

    public static NoteResponse fromDomain(Note note) {
        return new NoteResponse(
                note.id(),
                note.title(),
                note.createdAt());
    }
}
