// Generated by jails from art_ent_issue_priority_enum. Clean hand edits survive regeneration.
package com.example.demo.domain;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum IssuePriority {
    NONE("-"),
    HIGH("!"),
    URGENT("!!");

    private final String wire;

    IssuePriority(String wire) {
        this.wire = wire;
    }

    @JsonValue
    public String wire() {
        return this.wire;
    }

    @JsonCreator
    public static IssuePriority fromWire(String value) {
        for (IssuePriority candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "no IssuePriority with wire value '" + value + "'; expected one of -, !, !!");
    }
}
