// Generated by jails from art_op_tickets_by_status_query. Clean hand edits survive regeneration.
package com.example.demo.application.queries;

import com.example.demo.domain.Ticket;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

public interface TicketsByStatusQuery {
    List<Ticket> execute(Input input);

    public record Input(
        String status,
        Optional<String> category
    ) {

        public Input {
            Objects.requireNonNull(status, "status");
            status = status.trim();
            if (status.isEmpty()) {
                throw new IllegalArgumentException("status must not be blank");
            }
            category = Objects.requireNonNullElse(category, Optional.empty());
        }
    }
}
