-- Forward-only migration generated for a new record component.
alter table notes
add column created_at timestamptz;

-- Data plan supplied for rows that pre-date this field.
update notes
  set created_at = '2026-08-25T12:00:00Z'
  where created_at is null;

-- Forward-only nullability change generated by jails.
alter table notes
alter column created_at set not null;
