// Generated by jails from art_op_open_ticket_command. Clean hand edits survive regeneration.
package com.example.demo.application.commands;

import com.example.demo.domain.Ticket;
import java.util.Objects;

public interface OpenTicketCommand {
    String ROUTE = "POST /customer_api/open";

    Ticket execute(Input input);

    public record Input(
        String subject
    ) {

        public Input {
            Objects.requireNonNull(subject, "subject");
            subject = subject.trim();
            if (subject.isEmpty()) {
                throw new IllegalArgumentException("subject must not be blank");
            }
        }
    }
}
