// Generated by jails from art_op_note_created_event. Clean hand edits survive regeneration.
package com.example.demo.domain.events;

import java.util.Objects;
import java.util.UUID;

public record CreatedEvent(
    UUID id,
    String title
) {

    public CreatedEvent {
        Objects.requireNonNull(id, "id");
        Objects.requireNonNull(title, "title");
        title = title.trim();
        if (title.isEmpty()) {
            throw new IllegalArgumentException("title must not be blank");
        }
    }
}
