// Generated by jails from art_cmp_sealed_outcome_test. Clean hand edits survive regeneration.
package com.example.demo.domain;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

class OutcomeTest {

    private String describe(Outcome value) {
        return switch (value) {
            case Outcome.Accepted ignored -> "accepted";
            case Outcome.Rejected ignored -> "rejected";
        };
    }

    @Test
    void describesAccepted() {
        assertEquals("accepted", describe(new Outcome.Accepted()));
    }

    @Test
    void describesRejected() {
        assertEquals("rejected", describe(new Outcome.Rejected()));
    }
}
