// Generated by jails from art_ent_status_test. Clean hand edits survive regeneration.
package com.example.demo.domain;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

import org.junit.jupiter.api.Test;

class StatusTest {

    @Test
    void parsesItsOwnNames() {
        assertEquals(Status.ACTIVE, Status.valueOf("ACTIVE"));
    }

    /** The failure mode worth pinning: valueOf throws, it does not return null. */
    @Test
    void rejectsAnUnknownName() {
        assertThrows(IllegalArgumentException.class, () -> Status.valueOf("NOPE"));
    }

    @Test
    void declaresEveryConstantExactlyOnce() {
        assertEquals(2, Status.values().length);
    }
}
