-- Generated by jails from the accepted semantic schema.
create table authors (
    id bigint generated always as identity not null primary key,
    email text not null unique check (length(btrim(email)) > 0)
);
