-- Generated by jails from the accepted model.
create table owners (
    id uuid not null primary key,
    email text not null unique check (length(btrim(email)) > 0),
    created_at timestamptz default current_timestamp not null
);
