// Generated by jails from art_ent_note_dto_response. Clean hand edits survive regeneration.
package com.example.demo.web;

import com.example.demo.domain.Note;

public record NoteResponse(
    long id,
    String body,
    boolean seen,
    long version
) {

    public static NoteResponse fromDomain(Note note) {
        return new NoteResponse(
                note.id(),
                note.body(),
                note.seen(),
                note.version());
    }
}
