// Generated by jails from art_op_add_item_command. Clean hand edits survive regeneration.
package com.example.demo.application.commands;

import com.example.demo.domain.Item;
import java.util.Objects;
import java.util.UUID;

public interface AddItemCommand {

    Item execute(Input input);

    public record Input(
        UUID id,
        UUID ownerId,
        String name
    ) {

        public Input {
            Objects.requireNonNull(id, "id");
            Objects.requireNonNull(ownerId, "ownerId");
            Objects.requireNonNull(name, "name");
            name = name.trim();
            if (name.isEmpty()) {
                throw new IllegalArgumentException("name must not be blank");
            }
        }
    }
}
