// Generated by jails from art_app_api_error_test. Clean hand edits survive regeneration.
package com.example.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.util.Map;
import org.junit.jupiter.api.Test;

class ApiErrorTest {

    @Test
    void keepsWhatItWasGiven() {
        var value = ApiError.of("sample", "sample", Map.of());

        assertThat(value.code()).isEqualTo("sample");
        assertThat(value.message()).isEqualTo("sample");
        assertThat(value.details()).isEqualTo(Map.of());
    }

    @Test
    void rejectsANullComponent() {
        assertThatThrownBy(() -> ApiError.of(null, "sample", Map.of()))
                .isInstanceOf(NullPointerException.class)
                .hasMessageContaining("code");
    }

    @Test
    void trimsSurroundingWhitespace() {
        assertThat(ApiError.of("  trimmed  ", "sample", Map.of()).code()).isEqualTo("trimmed");
    }

    /** Blank is the failure a null check never catches. */
    @Test
    void rejectsBlankText() {
        assertThatThrownBy(() -> ApiError.of("   ", "sample", Map.of()))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("code");
    }
}
