// Generated by jails from art_ent_operator_dto_response. Clean hand edits survive regeneration.
package com.example.demo.web;

import com.example.demo.domain.Operator;

public record OperatorResponse(
    long id,
    String email
) {

    public static OperatorResponse fromDomain(Operator operator) {
        return new OperatorResponse(
                operator.id(),
                operator.email());
    }
}
