// Generated by jails from art_ent_article_http_controller_test. Clean hand edits survive regeneration.
package com.example.demo.web;

import static org.assertj.core.api.Assertions.assertThat;

import com.example.demo.domain.Article;
import com.example.demo.repository.ArticleRepository;
import com.example.demo.service.ArticleService;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import org.junit.jupiter.api.Test;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.assertj.MockMvcTester;

class ArticleControllerTest {

    private static final Article ROW = new Article(UUID.fromString("00000000-0000-0000-0000-000000000001"), "sample", "sample");

    private static final ArticleRepository REPOSITORY = new ArticleRepository() {
        @Override
        public Optional<Article> findById(UUID id) {
            return Optional.of(ROW);
        }

        @Override
        public List<Article> findAll() {
            return List.of(ROW);
        }

        @Override
        public Article save(Article value) {
            return value;
        }

        @Override
        public boolean deleteById(UUID id) {
            return true;
        }
    };

    private static final String CREATE_REQUEST =
            """
            {
              "title": "sample-title",
              "body": "sample-body"
            }""";

    private final MockMvcTester mvc = MockMvcTester.of(new ArticleController(new ArticleService(REPOSITORY)));

    @Test
    void theDocumentedCreateRequestIsAccepted() {
        assertThat(mvc.post().uri("/articles")
                .contentType(MediaType.APPLICATION_JSON)
                .content(CREATE_REQUEST))
                .hasStatus(201);
        assertThat(mvc.get().uri("/articles"))
                .hasStatusOk();
    }

    // Reader-owned tests belong below this stable boundary.
}
