// Generated by jails from art_ent_message_http. Clean hand edits survive regeneration.
package com.example.demo.ports.http;

import com.example.demo.domain.Message;

public interface MessageHttpPort {

    Message create(Message request);
}
