// Generated by jails from art_app_time_ordered_uuid. Clean hand edits survive regeneration.
package com.example.demo.domain;

import java.security.SecureRandom;
import java.util.UUID;

public final class TimeOrderedUuid {

    private static final SecureRandom RANDOM = new SecureRandom();

    private TimeOrderedUuid() {}

    public static UUID next() {
        byte[] value = new byte[16];
        RANDOM.nextBytes(value);
        long milliseconds = System.currentTimeMillis();
        value[0] = (byte) (milliseconds >>> 40);
        value[1] = (byte) (milliseconds >>> 32);
        value[2] = (byte) (milliseconds >>> 24);
        value[3] = (byte) (milliseconds >>> 16);
        value[4] = (byte) (milliseconds >>> 8);
        value[5] = (byte) milliseconds;
        value[6] = (byte) ((value[6] & 0x0f) | 0x70);
        value[8] = (byte) ((value[8] & 0x3f) | 0x80);
        long high = 0;
        long low = 0;
        for (int index = 0; index < 8; index++) {
            high = (high << 8) | (value[index] & 0xffL);
        }
        for (int index = 8; index < 16; index++) {
            low = (low << 8) | (value[index] & 0xffL);
        }
        return new UUID(high, low);
    }
}
