// Generated by jails from art_cmp_controller_verify_http_test. Clean hand edits survive regeneration.
package com.example.demo.web;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.test.web.servlet.assertj.MockMvcTester;

@SpringBootTest
@AutoConfigureMockMvc
class VerifyControllerTest {

    @Autowired private MockMvcTester mvc;

    @Test
    @Disabled("todo: implement the handler, then delete this @Disabled")
    void postAnswers() {
        assertThat(mvc.post().uri("/verify"))
                .hasStatus2xxSuccessful();
    }

    // Reader-owned tests belong below this stable boundary.
}
